// This file is auto-generated by @hey-api/openapi-ts

import { type HttpRequest, httpResource } from '@angular/common/http';

import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { DeleteEventsApiEventsByIdData, DeleteEventsApiEventsByIdResponse, GetEventsApiEventsByIdData, GetEventsApiEventsByIdResponse, GetEventsApiEventsNamesData, GetEventsApiEventsNamesResponse, GetEventsApiStreamData, GetEventsApiStreamResponse, ListEventsData, ListEventsResponse, PostEventsApiEventsData, PostEventsApiEventsResponse, PutEventsApiEventsByIdData, PutEventsApiEventsByIdResponse } from '../types.gen';

/**
 * List
 */
export const listEventsRequest = <ThrowOnError extends boolean = false>(options?: Options<ListEventsData, ThrowOnError>): HttpRequest<ListEventsResponse> => (options?.client ?? client).requestOptions<ListEventsResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/events/api/events',
    ...options
});

/**
 * Create
 */
export const postEventsApiEventsRequest = <ThrowOnError extends boolean = false>(options: Options<PostEventsApiEventsData, ThrowOnError>): HttpRequest<PostEventsApiEventsResponse> => (options?.client ?? client).requestOptions<PostEventsApiEventsResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'POST',
    url: '/events/api/events',
    ...options
});

/**
 * Names
 */
export const getEventsApiEventsNamesRequest = <ThrowOnError extends boolean = false>(options?: Options<GetEventsApiEventsNamesData, ThrowOnError>): HttpRequest<GetEventsApiEventsNamesResponse> => (options?.client ?? client).requestOptions<GetEventsApiEventsNamesResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/events/api/events/names',
    ...options
});

/**
 * Delete
 */
export const deleteEventsApiEventsByIdRequest = <ThrowOnError extends boolean = false>(options: Options<DeleteEventsApiEventsByIdData, ThrowOnError>): HttpRequest<DeleteEventsApiEventsByIdResponse> => (options?.client ?? client).requestOptions<DeleteEventsApiEventsByIdResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'DELETE',
    url: '/events/api/events/{id}',
    ...options
});

/**
 * Get
 */
export const getEventsApiEventsByIdRequest = <ThrowOnError extends boolean = false>(options: Options<GetEventsApiEventsByIdData, ThrowOnError>): HttpRequest<GetEventsApiEventsByIdResponse> => (options?.client ?? client).requestOptions<GetEventsApiEventsByIdResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/events/api/events/{id}',
    ...options
});

/**
 * Publish
 */
export const putEventsApiEventsByIdRequest = <ThrowOnError extends boolean = false>(options: Options<PutEventsApiEventsByIdData, ThrowOnError>): HttpRequest<PutEventsApiEventsByIdResponse> => (options?.client ?? client).requestOptions<PutEventsApiEventsByIdResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'PUT',
    url: '/events/api/events/{id}',
    ...options
});

/**
 * Live event stream (Server-Sent Events)
 *
 * Pushes each newly created event whose name is named by ?names= (comma-separated; '*' means everything; absent means nothing) as an SSE event whose id: field is the event id and whose data is the EventCreated envelope. Live only: no replay, no offset, no catch-up.
 */
export const getEventsApiStreamRequest = <ThrowOnError extends boolean = false>(options?: Options<GetEventsApiStreamData, ThrowOnError>): HttpRequest<GetEventsApiStreamResponse> => (options?.client ?? client).requestOptions<GetEventsApiStreamResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/events/api/stream',
    ...options
});

/**
 * List
 */
export const listEventsResource = <ThrowOnError extends boolean = false>(options?: () => Options<ListEventsData, ThrowOnError> | undefined) => httpResource<ListEventsResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? listEventsRequest(opts) : undefined;
});

/**
 * Create
 */
export const postEventsApiEventsResource = <ThrowOnError extends boolean = false>(options: () => Options<PostEventsApiEventsData, ThrowOnError> | undefined) => httpResource<PostEventsApiEventsResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? postEventsApiEventsRequest(opts) : undefined;
});

/**
 * Names
 */
export const getEventsApiEventsNamesResource = <ThrowOnError extends boolean = false>(options?: () => Options<GetEventsApiEventsNamesData, ThrowOnError> | undefined) => httpResource<GetEventsApiEventsNamesResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getEventsApiEventsNamesRequest(opts) : undefined;
});

/**
 * Delete
 */
export const deleteEventsApiEventsByIdResource = <ThrowOnError extends boolean = false>(options: () => Options<DeleteEventsApiEventsByIdData, ThrowOnError> | undefined) => httpResource<DeleteEventsApiEventsByIdResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? deleteEventsApiEventsByIdRequest(opts) : undefined;
});

/**
 * Get
 */
export const getEventsApiEventsByIdResource = <ThrowOnError extends boolean = false>(options: () => Options<GetEventsApiEventsByIdData, ThrowOnError> | undefined) => httpResource<GetEventsApiEventsByIdResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getEventsApiEventsByIdRequest(opts) : undefined;
});

/**
 * Publish
 */
export const putEventsApiEventsByIdResource = <ThrowOnError extends boolean = false>(options: () => Options<PutEventsApiEventsByIdData, ThrowOnError> | undefined) => httpResource<PutEventsApiEventsByIdResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? putEventsApiEventsByIdRequest(opts) : undefined;
});

/**
 * Live event stream (Server-Sent Events)
 *
 * Pushes each newly created event whose name is named by ?names= (comma-separated; '*' means everything; absent means nothing) as an SSE event whose id: field is the event id and whose data is the EventCreated envelope. Live only: no replay, no offset, no catch-up.
 */
export const getEventsApiStreamResource = <ThrowOnError extends boolean = false>(options?: () => Options<GetEventsApiStreamData, ThrowOnError> | undefined) => httpResource<GetEventsApiStreamResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getEventsApiStreamRequest(opts) : undefined;
});
