// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteGithostApiRepositoriesByRepoIdBranchesByNameData, DeleteGithostApiRepositoriesByRepoIdBranchesByNameErrors, DeleteGithostApiRepositoriesByRepoIdBranchesByNameResponses, GetGithostApiRepositoriesByRepoIdBranchesByNameData, GetGithostApiRepositoriesByRepoIdBranchesByNameErrors, GetGithostApiRepositoriesByRepoIdBranchesByNameResponses, GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesData, GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesErrors, GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesResponses, GetGithostApiRepositoriesByRepoIdContainsData, GetGithostApiRepositoriesByRepoIdContainsErrors, GetGithostApiRepositoriesByRepoIdContainsResponses, GetGithostApiRepositoriesByRepoIdData, GetGithostApiRepositoriesByRepoIdFileData, GetGithostApiRepositoriesByRepoIdFileResponses, GetGithostApiRepositoriesByRepoIdResponses, GetGithostApiRepositoriesByRepoIdTagsData, GetGithostApiRepositoriesByRepoIdTagsResponses, GetGithostApiRepositoriesByRepoIdTreeData, GetGithostApiRepositoriesByRepoIdTreeResponses, GetGithostApiRepositoriesData, GetGithostApiRepositoriesResponses, GetLocData, GetLocErrors, GetLocResponses, ListLocData, ListLocResponses, PostGithostApiRepositoriesByRepoIdCommitsData, PostGithostApiRepositoriesByRepoIdCommitsErrors, PostGithostApiRepositoriesByRepoIdCommitsResponses, PostGithostApiRepositoriesByRepoIdMergesData, PostGithostApiRepositoriesByRepoIdMergesErrors, PostGithostApiRepositoriesByRepoIdMergesResponses, PostGithostApiRepositoriesByRepoIdTagsData, PostGithostApiRepositoriesByRepoIdTagsErrors, PostGithostApiRepositoriesByRepoIdTagsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Lines of code of every repository's default branch
 *
 * One row per repository this host holds, or per named repositoryId it holds. COUNTED rows carry the numbers; PENDING rows are queued for counting by this call; EMPTY rows have no commit yet.
 */
export const listLoc = <ThrowOnError extends boolean = false>(options?: Options<ListLocData, ThrowOnError>): RequestResult<ListLocResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListLocResponses, unknown, ThrowOnError>({ url: '/githost/api/loc', ...options });

/**
 * List
 */
export const getGithostApiRepositories = <ThrowOnError extends boolean = false>(options?: Options<GetGithostApiRepositoriesData, ThrowOnError>): RequestResult<GetGithostApiRepositoriesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetGithostApiRepositoriesResponses, unknown, ThrowOnError>({ url: '/githost/api/repositories', ...options });

/**
 * Describe
 */
export const getGithostApiRepositoriesByRepoId = <ThrowOnError extends boolean = false>(options: Options<GetGithostApiRepositoriesByRepoIdData, ThrowOnError>): RequestResult<GetGithostApiRepositoriesByRepoIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetGithostApiRepositoriesByRepoIdResponses, unknown, ThrowOnError>({ url: '/githost/api/repositories/{repoId}', ...options });

/**
 * Delete Branch
 */
export const deleteGithostApiRepositoriesByRepoIdBranchesByName = <ThrowOnError extends boolean = false>(options: Options<DeleteGithostApiRepositoriesByRepoIdBranchesByNameData, ThrowOnError>): RequestResult<DeleteGithostApiRepositoriesByRepoIdBranchesByNameResponses, DeleteGithostApiRepositoriesByRepoIdBranchesByNameErrors, ThrowOnError> => (options.client ?? client).delete<DeleteGithostApiRepositoriesByRepoIdBranchesByNameResponses, DeleteGithostApiRepositoriesByRepoIdBranchesByNameErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/githost/api/repositories/{repoId}/branches/{name}',
    ...options
});

/**
 * Branch
 */
export const getGithostApiRepositoriesByRepoIdBranchesByName = <ThrowOnError extends boolean = false>(options: Options<GetGithostApiRepositoriesByRepoIdBranchesByNameData, ThrowOnError>): RequestResult<GetGithostApiRepositoriesByRepoIdBranchesByNameResponses, GetGithostApiRepositoriesByRepoIdBranchesByNameErrors, ThrowOnError> => (options.client ?? client).get<GetGithostApiRepositoriesByRepoIdBranchesByNameResponses, GetGithostApiRepositoriesByRepoIdBranchesByNameErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/githost/api/repositories/{repoId}/branches/{name}',
    ...options
});

/**
 * List
 */
export const getGithostApiRepositoriesByRepoIdCommitSubjectBypasses = <ThrowOnError extends boolean = false>(options: Options<GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesData, ThrowOnError>): RequestResult<GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesResponses, GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesErrors, ThrowOnError> => (options.client ?? client).get<GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesResponses, GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/githost/api/repositories/{repoId}/commit-subject-bypasses',
    ...options
});

/**
 * Commit
 */
export const postGithostApiRepositoriesByRepoIdCommits = <ThrowOnError extends boolean = false>(options: Options<PostGithostApiRepositoriesByRepoIdCommitsData, ThrowOnError>): RequestResult<PostGithostApiRepositoriesByRepoIdCommitsResponses, PostGithostApiRepositoriesByRepoIdCommitsErrors, ThrowOnError> => (options.client ?? client).post<PostGithostApiRepositoriesByRepoIdCommitsResponses, PostGithostApiRepositoriesByRepoIdCommitsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/githost/api/repositories/{repoId}/commits',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Contains
 */
export const getGithostApiRepositoriesByRepoIdContains = <ThrowOnError extends boolean = false>(options: Options<GetGithostApiRepositoriesByRepoIdContainsData, ThrowOnError>): RequestResult<GetGithostApiRepositoriesByRepoIdContainsResponses, GetGithostApiRepositoriesByRepoIdContainsErrors, ThrowOnError> => (options.client ?? client).get<GetGithostApiRepositoriesByRepoIdContainsResponses, GetGithostApiRepositoriesByRepoIdContainsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/githost/api/repositories/{repoId}/contains',
    ...options
});

/**
 * File
 */
export const getGithostApiRepositoriesByRepoIdFile = <ThrowOnError extends boolean = false>(options: Options<GetGithostApiRepositoriesByRepoIdFileData, ThrowOnError>): RequestResult<GetGithostApiRepositoriesByRepoIdFileResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetGithostApiRepositoriesByRepoIdFileResponses, unknown, ThrowOnError>({ url: '/githost/api/repositories/{repoId}/file', ...options });

/**
 * Lines of code of one repository at one commit (default: the default branch)
 */
export const getLoc = <ThrowOnError extends boolean = false>(options: Options<GetLocData, ThrowOnError>): RequestResult<GetLocResponses, GetLocErrors, ThrowOnError> => (options.client ?? client).get<GetLocResponses, GetLocErrors, ThrowOnError>({ url: '/githost/api/repositories/{repoId}/loc', ...options });

/**
 * Merge
 */
export const postGithostApiRepositoriesByRepoIdMerges = <ThrowOnError extends boolean = false>(options: Options<PostGithostApiRepositoriesByRepoIdMergesData, ThrowOnError>): RequestResult<PostGithostApiRepositoriesByRepoIdMergesResponses, PostGithostApiRepositoriesByRepoIdMergesErrors, ThrowOnError> => (options.client ?? client).post<PostGithostApiRepositoriesByRepoIdMergesResponses, PostGithostApiRepositoriesByRepoIdMergesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/githost/api/repositories/{repoId}/merges',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Tags
 */
export const getGithostApiRepositoriesByRepoIdTags = <ThrowOnError extends boolean = false>(options: Options<GetGithostApiRepositoriesByRepoIdTagsData, ThrowOnError>): RequestResult<GetGithostApiRepositoriesByRepoIdTagsResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetGithostApiRepositoriesByRepoIdTagsResponses, unknown, ThrowOnError>({ url: '/githost/api/repositories/{repoId}/tags', ...options });

/**
 * Tag
 */
export const postGithostApiRepositoriesByRepoIdTags = <ThrowOnError extends boolean = false>(options: Options<PostGithostApiRepositoriesByRepoIdTagsData, ThrowOnError>): RequestResult<PostGithostApiRepositoriesByRepoIdTagsResponses, PostGithostApiRepositoriesByRepoIdTagsErrors, ThrowOnError> => (options.client ?? client).post<PostGithostApiRepositoriesByRepoIdTagsResponses, PostGithostApiRepositoriesByRepoIdTagsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/githost/api/repositories/{repoId}/tags',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Tree
 */
export const getGithostApiRepositoriesByRepoIdTree = <ThrowOnError extends boolean = false>(options: Options<GetGithostApiRepositoriesByRepoIdTreeData, ThrowOnError>): RequestResult<GetGithostApiRepositoriesByRepoIdTreeResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetGithostApiRepositoriesByRepoIdTreeResponses, unknown, ThrowOnError>({ url: '/githost/api/repositories/{repoId}/tree', ...options });
