// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Author = {
    name?: string;
    email?: string;
};

export type BypassRecord = {
    id?: Uuid;
    repositoryId?: string;
    pusher?: string;
    reason?: string;
    refs?: Array<string>;
    commits?: Array<string>;
    usedAt?: Instant;
};

export type BypassesResponse = {
    bypasses?: Array<BypassRecord>;
};

export type Category = 'CODE' | 'DATA' | 'DOCS';

export type CommitRequest = {
    ref?: string;
    message?: string;
    files?: {
        [key: string]: string;
    };
    deletePaths?: Array<string>;
    gitlinks?: {
        [key: string]: string;
    };
    author?: Author;
};

export type ErrorBody = {
    error?: string;
};

export type Instant = string;

export type LanguageLoc = {
    language?: string;
    category?: Category;
    mainLines?: number;
    testLines?: number;
};

export type LocEntry = {
    repositoryId?: string;
    commitSha?: string;
    status?: LocStatus;
    languages?: Array<LanguageLoc>;
};

export type LocListResponse = {
    entries?: Array<LocEntry>;
};

export type LocResponse = {
    commitSha?: string;
    languages?: Array<LanguageLoc>;
};

export type LocStatus = 'COUNTED' | 'STALE' | 'PENDING' | 'EMPTY';

export type MergeRequest = {
    target?: string;
    sources?: Array<string>;
    message?: string;
    author?: Author;
    resolutions?: Array<Resolution>;
};

export type RepositoriesResponse = {
    repositories?: Array<RepositoryRecord>;
};

export type RepositoryRecord = {
    id?: string;
    protectDefaultBranch?: boolean;
};

export type Resolution = {
    path?: string;
    gitlink?: string;
};

export type TagRequest = {
    name?: string;
    sha?: string;
    message?: string;
    author?: Author;
};

export type Uuid = string;

export type ListLocData = {
    body?: never;
    path?: never;
    query?: {
        repositoryId?: Array<string>;
    };
    url: '/githost/api/loc';
};

export type ListLocResponses = {
    /**
     * OK
     */
    200: LocListResponse;
};

export type ListLocResponse = ListLocResponses[keyof ListLocResponses];

export type GetGithostApiRepositoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/githost/api/repositories';
};

export type GetGithostApiRepositoriesResponses = {
    /**
     * OK
     */
    200: RepositoriesResponse;
};

export type GetGithostApiRepositoriesResponse = GetGithostApiRepositoriesResponses[keyof GetGithostApiRepositoriesResponses];

export type GetGithostApiRepositoriesByRepoIdData = {
    body?: never;
    path: {
        repoId: string;
    };
    query?: never;
    url: '/githost/api/repositories/{repoId}';
};

export type GetGithostApiRepositoriesByRepoIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteGithostApiRepositoriesByRepoIdBranchesByNameData = {
    body?: never;
    path: {
        name: string;
        repoId: string;
    };
    query?: never;
    url: '/githost/api/repositories/{repoId}/branches/{name}';
};

export type DeleteGithostApiRepositoriesByRepoIdBranchesByNameErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type DeleteGithostApiRepositoriesByRepoIdBranchesByNameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetGithostApiRepositoriesByRepoIdBranchesByNameData = {
    body?: never;
    path: {
        name: string;
        repoId: string;
    };
    query?: never;
    url: '/githost/api/repositories/{repoId}/branches/{name}';
};

export type GetGithostApiRepositoriesByRepoIdBranchesByNameErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetGithostApiRepositoriesByRepoIdBranchesByNameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesData = {
    body?: never;
    path: {
        repoId: string;
    };
    query?: never;
    url: '/githost/api/repositories/{repoId}/commit-subject-bypasses';
};

export type GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesResponses = {
    /**
     * OK
     */
    200: BypassesResponse;
};

export type GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesResponse = GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesResponses[keyof GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesResponses];

export type PostGithostApiRepositoriesByRepoIdCommitsData = {
    body: CommitRequest;
    path: {
        repoId: string;
    };
    query?: never;
    url: '/githost/api/repositories/{repoId}/commits';
};

export type PostGithostApiRepositoriesByRepoIdCommitsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostGithostApiRepositoriesByRepoIdCommitsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetGithostApiRepositoriesByRepoIdContainsData = {
    body?: never;
    path: {
        repoId: string;
    };
    query?: {
        commit?: string;
        in?: string;
    };
    url: '/githost/api/repositories/{repoId}/contains';
};

export type GetGithostApiRepositoriesByRepoIdContainsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetGithostApiRepositoriesByRepoIdContainsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetGithostApiRepositoriesByRepoIdFileData = {
    body?: never;
    path: {
        repoId: string;
    };
    query?: {
        path?: string;
        rev?: string;
    };
    url: '/githost/api/repositories/{repoId}/file';
};

export type GetGithostApiRepositoriesByRepoIdFileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetLocData = {
    body?: never;
    path: {
        repoId: string;
    };
    query?: {
        rev?: string;
    };
    url: '/githost/api/repositories/{repoId}/loc';
};

export type GetLocErrors = {
    /**
     * No such repository or revision
     */
    404: ErrorBody;
};

export type GetLocError = GetLocErrors[keyof GetLocErrors];

export type GetLocResponses = {
    /**
     * OK
     */
    200: LocResponse;
};

export type GetLocResponse = GetLocResponses[keyof GetLocResponses];

export type PostGithostApiRepositoriesByRepoIdMergesData = {
    body: MergeRequest;
    path: {
        repoId: string;
    };
    query?: never;
    url: '/githost/api/repositories/{repoId}/merges';
};

export type PostGithostApiRepositoriesByRepoIdMergesErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostGithostApiRepositoriesByRepoIdMergesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetGithostApiRepositoriesByRepoIdTagsData = {
    body?: never;
    path: {
        repoId: string;
    };
    query?: {
        limit?: number;
    };
    url: '/githost/api/repositories/{repoId}/tags';
};

export type GetGithostApiRepositoriesByRepoIdTagsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostGithostApiRepositoriesByRepoIdTagsData = {
    body: TagRequest;
    path: {
        repoId: string;
    };
    query?: never;
    url: '/githost/api/repositories/{repoId}/tags';
};

export type PostGithostApiRepositoriesByRepoIdTagsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostGithostApiRepositoriesByRepoIdTagsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetGithostApiRepositoriesByRepoIdTreeData = {
    body?: never;
    path: {
        repoId: string;
    };
    query?: {
        rev?: string;
    };
    url: '/githost/api/repositories/{repoId}/tree';
};

export type GetGithostApiRepositoriesByRepoIdTreeResponses = {
    /**
     * OK
     */
    200: unknown;
};
