// This file is auto-generated by @hey-api/openapi-ts

import { type HttpRequest, httpResource } from '@angular/common/http';

import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { DeleteGithostApiRepositoriesByRepoIdBranchesByNameData, GetGithostApiRepositoriesByRepoIdBranchesByNameData, GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesData, GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesResponse, GetGithostApiRepositoriesByRepoIdContainsData, GetGithostApiRepositoriesByRepoIdData, GetGithostApiRepositoriesByRepoIdFileData, GetGithostApiRepositoriesByRepoIdTagsData, GetGithostApiRepositoriesByRepoIdTreeData, GetGithostApiRepositoriesData, GetGithostApiRepositoriesResponse, GetLocData, GetLocResponse, ListLocData, ListLocResponse, PostGithostApiRepositoriesByRepoIdCommitsData, PostGithostApiRepositoriesByRepoIdMergesData, PostGithostApiRepositoriesByRepoIdTagsData } from '../types.gen';

/**
 * Lines of code of every repository's default branch
 *
 * One row per repository this host holds, or per named repositoryId it holds. COUNTED rows carry the default branch's numbers; STALE rows carry the newest stored numbers of an older commit while the tip is counted; PENDING rows were never counted; EMPTY rows have no commit yet. This call queues every tip that is not counted.
 */
export const listLocRequest = <ThrowOnError extends boolean = false>(options?: Options<ListLocData, ThrowOnError>): HttpRequest<ListLocResponse> => (options?.client ?? client).requestOptions<ListLocResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/githost/api/loc',
    ...options
});

/**
 * List
 */
export const getGithostApiRepositoriesRequest = <ThrowOnError extends boolean = false>(options?: Options<GetGithostApiRepositoriesData, ThrowOnError>): HttpRequest<GetGithostApiRepositoriesResponse> => (options?.client ?? client).requestOptions<GetGithostApiRepositoriesResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/githost/api/repositories',
    ...options
});

/**
 * Describe
 */
export const getGithostApiRepositoriesByRepoIdRequest = <ThrowOnError extends boolean = false>(options: Options<GetGithostApiRepositoriesByRepoIdData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/githost/api/repositories/{repoId}',
    ...options
});

/**
 * Delete Branch
 */
export const deleteGithostApiRepositoriesByRepoIdBranchesByNameRequest = <ThrowOnError extends boolean = false>(options: Options<DeleteGithostApiRepositoriesByRepoIdBranchesByNameData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'DELETE',
    url: '/githost/api/repositories/{repoId}/branches/{name}',
    ...options
});

/**
 * Branch
 */
export const getGithostApiRepositoriesByRepoIdBranchesByNameRequest = <ThrowOnError extends boolean = false>(options: Options<GetGithostApiRepositoriesByRepoIdBranchesByNameData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/githost/api/repositories/{repoId}/branches/{name}',
    ...options
});

/**
 * List
 */
export const getGithostApiRepositoriesByRepoIdCommitSubjectBypassesRequest = <ThrowOnError extends boolean = false>(options: Options<GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesData, ThrowOnError>): HttpRequest<GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesResponse> => (options?.client ?? client).requestOptions<GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/githost/api/repositories/{repoId}/commit-subject-bypasses',
    ...options
});

/**
 * Commit
 */
export const postGithostApiRepositoriesByRepoIdCommitsRequest = <ThrowOnError extends boolean = false>(options: Options<PostGithostApiRepositoriesByRepoIdCommitsData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'POST',
    url: '/githost/api/repositories/{repoId}/commits',
    ...options
});

/**
 * Contains
 */
export const getGithostApiRepositoriesByRepoIdContainsRequest = <ThrowOnError extends boolean = false>(options: Options<GetGithostApiRepositoriesByRepoIdContainsData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/githost/api/repositories/{repoId}/contains',
    ...options
});

/**
 * File
 */
export const getGithostApiRepositoriesByRepoIdFileRequest = <ThrowOnError extends boolean = false>(options: Options<GetGithostApiRepositoriesByRepoIdFileData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/githost/api/repositories/{repoId}/file',
    ...options
});

/**
 * Lines of code of one repository at one commit (default: the default branch)
 */
export const getLocRequest = <ThrowOnError extends boolean = false>(options: Options<GetLocData, ThrowOnError>): HttpRequest<GetLocResponse> => (options?.client ?? client).requestOptions<GetLocResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/githost/api/repositories/{repoId}/loc',
    ...options
});

/**
 * Merge
 */
export const postGithostApiRepositoriesByRepoIdMergesRequest = <ThrowOnError extends boolean = false>(options: Options<PostGithostApiRepositoriesByRepoIdMergesData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'POST',
    url: '/githost/api/repositories/{repoId}/merges',
    ...options
});

/**
 * Tags
 */
export const getGithostApiRepositoriesByRepoIdTagsRequest = <ThrowOnError extends boolean = false>(options: Options<GetGithostApiRepositoriesByRepoIdTagsData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/githost/api/repositories/{repoId}/tags',
    ...options
});

/**
 * Tag
 */
export const postGithostApiRepositoriesByRepoIdTagsRequest = <ThrowOnError extends boolean = false>(options: Options<PostGithostApiRepositoriesByRepoIdTagsData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'POST',
    url: '/githost/api/repositories/{repoId}/tags',
    ...options
});

/**
 * Tree
 */
export const getGithostApiRepositoriesByRepoIdTreeRequest = <ThrowOnError extends boolean = false>(options: Options<GetGithostApiRepositoriesByRepoIdTreeData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/githost/api/repositories/{repoId}/tree',
    ...options
});

/**
 * Lines of code of every repository's default branch
 *
 * One row per repository this host holds, or per named repositoryId it holds. COUNTED rows carry the default branch's numbers; STALE rows carry the newest stored numbers of an older commit while the tip is counted; PENDING rows were never counted; EMPTY rows have no commit yet. This call queues every tip that is not counted.
 */
export const listLocResource = <ThrowOnError extends boolean = false>(options?: () => Options<ListLocData, ThrowOnError> | undefined) => httpResource<ListLocResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? listLocRequest(opts) : undefined;
});

/**
 * List
 */
export const getGithostApiRepositoriesResource = <ThrowOnError extends boolean = false>(options?: () => Options<GetGithostApiRepositoriesData, ThrowOnError> | undefined) => httpResource<GetGithostApiRepositoriesResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getGithostApiRepositoriesRequest(opts) : undefined;
});

/**
 * Describe
 */
export const getGithostApiRepositoriesByRepoIdResource = <ThrowOnError extends boolean = false>(options: () => Options<GetGithostApiRepositoriesByRepoIdData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? getGithostApiRepositoriesByRepoIdRequest(opts) : undefined;
});

/**
 * Delete Branch
 */
export const deleteGithostApiRepositoriesByRepoIdBranchesByNameResource = <ThrowOnError extends boolean = false>(options: () => Options<DeleteGithostApiRepositoriesByRepoIdBranchesByNameData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? deleteGithostApiRepositoriesByRepoIdBranchesByNameRequest(opts) : undefined;
});

/**
 * Branch
 */
export const getGithostApiRepositoriesByRepoIdBranchesByNameResource = <ThrowOnError extends boolean = false>(options: () => Options<GetGithostApiRepositoriesByRepoIdBranchesByNameData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? getGithostApiRepositoriesByRepoIdBranchesByNameRequest(opts) : undefined;
});

/**
 * List
 */
export const getGithostApiRepositoriesByRepoIdCommitSubjectBypassesResource = <ThrowOnError extends boolean = false>(options: () => Options<GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesData, ThrowOnError> | undefined) => httpResource<GetGithostApiRepositoriesByRepoIdCommitSubjectBypassesResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getGithostApiRepositoriesByRepoIdCommitSubjectBypassesRequest(opts) : undefined;
});

/**
 * Commit
 */
export const postGithostApiRepositoriesByRepoIdCommitsResource = <ThrowOnError extends boolean = false>(options: () => Options<PostGithostApiRepositoriesByRepoIdCommitsData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? postGithostApiRepositoriesByRepoIdCommitsRequest(opts) : undefined;
});

/**
 * Contains
 */
export const getGithostApiRepositoriesByRepoIdContainsResource = <ThrowOnError extends boolean = false>(options: () => Options<GetGithostApiRepositoriesByRepoIdContainsData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? getGithostApiRepositoriesByRepoIdContainsRequest(opts) : undefined;
});

/**
 * File
 */
export const getGithostApiRepositoriesByRepoIdFileResource = <ThrowOnError extends boolean = false>(options: () => Options<GetGithostApiRepositoriesByRepoIdFileData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? getGithostApiRepositoriesByRepoIdFileRequest(opts) : undefined;
});

/**
 * Lines of code of one repository at one commit (default: the default branch)
 */
export const getLocResource = <ThrowOnError extends boolean = false>(options: () => Options<GetLocData, ThrowOnError> | undefined) => httpResource<GetLocResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getLocRequest(opts) : undefined;
});

/**
 * Merge
 */
export const postGithostApiRepositoriesByRepoIdMergesResource = <ThrowOnError extends boolean = false>(options: () => Options<PostGithostApiRepositoriesByRepoIdMergesData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? postGithostApiRepositoriesByRepoIdMergesRequest(opts) : undefined;
});

/**
 * Tags
 */
export const getGithostApiRepositoriesByRepoIdTagsResource = <ThrowOnError extends boolean = false>(options: () => Options<GetGithostApiRepositoriesByRepoIdTagsData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? getGithostApiRepositoriesByRepoIdTagsRequest(opts) : undefined;
});

/**
 * Tag
 */
export const postGithostApiRepositoriesByRepoIdTagsResource = <ThrowOnError extends boolean = false>(options: () => Options<PostGithostApiRepositoriesByRepoIdTagsData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? postGithostApiRepositoriesByRepoIdTagsRequest(opts) : undefined;
});

/**
 * Tree
 */
export const getGithostApiRepositoriesByRepoIdTreeResource = <ThrowOnError extends boolean = false>(options: () => Options<GetGithostApiRepositoriesByRepoIdTreeData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? getGithostApiRepositoriesByRepoIdTreeRequest(opts) : undefined;
});
