// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AdopterDto = {
    repository?: string;
    catalogId?: string;
    repositoryStatus?: string;
    archetype?: string;
    depth?: number;
    via?: Array<string>;
    state?: string;
    adoptedVersion?: string;
    adoptedAt?: Instant;
};

export type AdoptionJourneyDto = {
    repository?: string;
    catalogId?: string;
    version?: string;
    packages?: Array<PackageDto>;
    adopters?: Array<AdopterDto>;
};

export type ArtifactDependentsDto = {
    ecosystem?: string;
    name?: string;
    latest?: string;
    dependents?: Array<DependentDto>;
};

export type ArtifactDto = {
    ecosystem?: string;
    name?: string;
    repository?: string;
    latest?: string;
    version?: string;
    occurredAt?: Instant;
    sbomStatus?: string;
    dependentCount?: number;
    behindCount?: number;
};

export type ArtifactPinDto = {
    ecosystem?: string;
    name?: string;
    version?: string;
    repository?: string;
    manifestPath?: string;
    via?: string;
};

export type BaselinesRequest = {
    workItem?: string;
};

export type BumpDto = {
    id?: Uuid;
    repository?: string;
    group?: string;
    mode?: string;
    branch?: string;
    environment?: string;
    trigger?: string;
    status?: string;
    ciEventId?: string;
    ciRunId?: string;
    ciRunIds?: Array<string>;
    configPath?: string;
    ciRunStatus?: string;
    startedAt?: Instant;
    finishedAt?: Instant;
    message?: string;
    resultSha?: string;
    releaseRequestId?: string;
    releaseState?: string;
    releaseDetail?: string;
    releaseStateAt?: Instant;
    changes?: Array<Change>;
};

export type BumpWindowDto = {
    openedAt?: Instant;
    closesAt?: Instant;
    open?: boolean;
    outcome?: string;
    summary?: string;
    inFlight?: number;
    allowed?: number;
    ciActive?: number;
    owed?: number;
    held?: number;
    stalled?: Array<StalledBumpDto>;
    queue?: Array<OwedBumpDto>;
    next?: string;
};

export type Change = {
    ecosystem?: string;
    manifestPath?: string;
    name?: string;
    from?: string;
    to?: string;
    location?: string;
};

export type DependencyDto = {
    ecosystem?: string;
    name?: string;
    latest?: string;
    checkedAt?: Instant;
    error?: string;
    pins?: Array<DependencyPinDto>;
};

export type DependencyPinDto = {
    repository?: string;
    version?: string;
    manifestPath?: string;
    pending?: boolean;
};

export type DependentDto = {
    artifactEcosystem?: string;
    artifactName?: string;
    artifactVersion?: string;
    repository?: string;
    embeddedVersion?: string;
    direct?: boolean;
    occurredAt?: Instant;
    sbomStatus?: string;
};

export type DependentsDto = {
    ecosystem?: string;
    name?: string;
    latest?: string;
    dependents?: Array<DependentDto>;
};

export type DownstreamDto = {
    repository?: string;
    catalogId?: string;
    downstream?: Array<EntryDto>;
};

export type EntryDto = {
    repository?: string;
    catalogId?: string;
    archetype?: string;
    depth?: number;
    via?: Array<string>;
};

export type EntryDto1 = {
    project?: string;
    repository?: string;
    ecosystem?: string;
    name?: string;
    version?: string;
    reason?: string;
};

export type GroupDto = {
    name?: string;
    source?: string;
    kind?: string;
    branch?: string;
    state?: string;
    headSha?: string;
    pending?: number;
};

export type IngestRequest = {
    ecosystem?: string;
    name?: string;
    version?: string;
};

export type Instant = string;

export type OwedBumpDto = {
    repository?: string;
    group?: string;
    changes?: number;
    reason?: string;
    detail?: string;
};

export type PackageDto = {
    ecosystem?: string;
    name?: string;
};

export type PendingBumpsDto = {
    bumps?: Array<BumpDto>;
};

export type PinDto = {
    manifestPath?: string;
    ecosystem?: string;
    name?: string;
    version?: string;
    range?: string;
    kind?: string;
    latest?: string;
    latestError?: string;
    pending?: boolean;
    group?: string;
    location?: string;
    scope?: string;
};

export type PinSourceDto = {
    generatedAt?: Instant;
    repositories?: Array<RepositoryStateDto>;
    pins?: Array<ArtifactPinDto>;
};

export type RepositoryDependentsDto = {
    repository?: string;
    artifacts?: Array<ArtifactDependentsDto>;
};

export type RepositoryDetailDto = {
    name?: string;
    project?: string;
    archetype?: string;
    lastScanAt?: Instant;
    headSha?: string;
    status?: string;
    message?: string;
    pending?: number;
    groups?: Array<GroupDto>;
    pins?: Array<PinDto>;
    transitives?: Array<TransitiveDto>;
};

export type RepositoryDto = {
    name?: string;
    project?: string;
    archetype?: string;
    lastScanAt?: Instant;
    headSha?: string;
    status?: string;
    message?: string;
    pending?: number;
    groups?: Array<GroupDto>;
};

export type RepositoryStateDto = {
    name?: string;
    status?: string;
    lastScanAt?: Instant;
    headSha?: string;
};

export type SbomCheckReportDto = {
    ranAt?: Instant;
    filed?: boolean;
    entries?: Array<EntryDto1>;
    warnings?: Array<string>;
    tickets?: Array<TicketDto>;
};

export type ScanDto = {
    id?: Uuid;
    scope?: string;
    repository?: string;
    trigger?: string;
    status?: string;
    startedAt?: Instant;
    finishedAt?: Instant;
    message?: string;
};

export type StalledBumpDto = {
    repository?: string;
    group?: string;
    releaseRequestId?: string;
    state?: string;
    reason?: string;
};

export type StartScanRequest = {
    scope?: string;
    repository?: string;
};

export type TargetedBumpRequest = {
    branch?: string;
    changes?: Array<Change>;
};

export type TicketDto = {
    project?: string;
    ecosystem?: string;
    name?: string;
    ticketSlug?: string;
    versions?: Array<string>;
};

export type TransitiveDto = {
    ecosystem?: string;
    name?: string;
    version?: string;
    via?: string;
    behind?: boolean;
};

export type Uuid = string;

export type GetMaintenanceApiAdoptionByReleaseData = {
    body?: never;
    path?: never;
    query?: {
        repository?: string;
        version?: string;
    };
    url: '/maintenance/api/adoption/by-release';
};

export type GetMaintenanceApiAdoptionByReleaseErrors = {
    /**
     * Both repository and version are required
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetMaintenanceApiAdoptionByReleaseResponses = {
    /**
     * The journey
     */
    200: AdoptionJourneyDto;
};

export type GetMaintenanceApiAdoptionByReleaseResponse = GetMaintenanceApiAdoptionByReleaseResponses[keyof GetMaintenanceApiAdoptionByReleaseResponses];

export type GetMaintenanceApiArtifactsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/maintenance/api/artifacts';
};

export type GetMaintenanceApiArtifactsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetMaintenanceApiArtifactsResponses = {
    /**
     * The artifacts
     */
    200: Array<ArtifactDto>;
};

export type GetMaintenanceApiArtifactsResponse = GetMaintenanceApiArtifactsResponses[keyof GetMaintenanceApiArtifactsResponses];

export type PostMaintenanceApiArtifactsIngestData = {
    body: IngestRequest;
    path?: never;
    query?: never;
    url: '/maintenance/api/artifacts/ingest';
};

export type PostMaintenanceApiArtifactsIngestErrors = {
    /**
     * Unknown ecosystem, or no name or version
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostMaintenanceApiArtifactsIngestResponses = {
    /**
     * Queued; the id is the artifact row
     */
    202: unknown;
};

export type ListBumpsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        repository?: string;
    };
    url: '/maintenance/api/bumps';
};

export type ListBumpsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type ListBumpsResponses = {
    /**
     * The bumps
     */
    200: Array<BumpDto>;
};

export type ListBumpsResponse = ListBumpsResponses[keyof ListBumpsResponses];

export type ListPendingBumpsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/maintenance/api/bumps/pending';
};

export type ListPendingBumpsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type ListPendingBumpsResponses = {
    /**
     * The pending bumps
     */
    200: PendingBumpsDto;
};

export type ListPendingBumpsResponse = ListPendingBumpsResponses[keyof ListPendingBumpsResponses];

export type DeleteMaintenanceApiBumpsWindowData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/maintenance/api/bumps/window';
};

export type DeleteMaintenanceApiBumpsWindowErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type DeleteMaintenanceApiBumpsWindowResponses = {
    /**
     * There is no window now
     */
    204: void;
};

export type DeleteMaintenanceApiBumpsWindowResponse = DeleteMaintenanceApiBumpsWindowResponses[keyof DeleteMaintenanceApiBumpsWindowResponses];

export type GetBumpWindowData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/maintenance/api/bumps/window';
};

export type GetBumpWindowErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetBumpWindowResponses = {
    /**
     * The window, or the reason there is none
     */
    200: BumpWindowDto;
};

export type GetBumpWindowResponse = GetBumpWindowResponses[keyof GetBumpWindowResponses];

export type PostMaintenanceApiBumpsWindowData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/maintenance/api/bumps/window';
};

export type PostMaintenanceApiBumpsWindowErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostMaintenanceApiBumpsWindowResponses = {
    /**
     * The window that is now open
     */
    200: BumpWindowDto;
};

export type PostMaintenanceApiBumpsWindowResponse = PostMaintenanceApiBumpsWindowResponses[keyof PostMaintenanceApiBumpsWindowResponses];

export type GetBumpData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/maintenance/api/bumps/{id}';
};

export type GetBumpErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such bump
     */
    404: unknown;
};

export type GetBumpResponses = {
    /**
     * The bump
     */
    200: BumpDto;
};

export type GetBumpResponse = GetBumpResponses[keyof GetBumpResponses];

export type GetMaintenanceApiDependenciesData = {
    body?: never;
    path?: never;
    query?: {
        kind?: string;
        name?: string;
    };
    url: '/maintenance/api/dependencies';
};

export type GetMaintenanceApiDependenciesErrors = {
    /**
     * kind is neither INTERNAL nor EXTERNAL
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetMaintenanceApiDependenciesResponses = {
    /**
     * The dependencies
     */
    200: Array<DependencyDto>;
};

export type GetMaintenanceApiDependenciesResponse = GetMaintenanceApiDependenciesResponses[keyof GetMaintenanceApiDependenciesResponses];

export type GetMaintenanceApiDependenciesDependentsData = {
    body?: never;
    path?: never;
    query?: {
        all?: boolean;
        ecosystem?: string;
        name?: string;
    };
    url: '/maintenance/api/dependencies/dependents';
};

export type GetMaintenanceApiDependenciesDependentsErrors = {
    /**
     * Unknown ecosystem, or no name
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetMaintenanceApiDependenciesDependentsResponses = {
    /**
     * The dependents
     */
    200: DependentsDto;
};

export type GetMaintenanceApiDependenciesDependentsResponse = GetMaintenanceApiDependenciesDependentsResponses[keyof GetMaintenanceApiDependenciesDependentsResponses];

export type GetMaintenanceApiPinsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/maintenance/api/pins';
};

export type GetMaintenanceApiPinsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * The inventory holds no repository at all
     */
    503: unknown;
};

export type GetMaintenanceApiPinsResponses = {
    /**
     * The pins, with the inventory's freshness
     */
    200: PinSourceDto;
};

export type GetMaintenanceApiPinsResponse = GetMaintenanceApiPinsResponses[keyof GetMaintenanceApiPinsResponses];

export type GetMaintenanceApiRepositoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/maintenance/api/repositories';
};

export type GetMaintenanceApiRepositoriesErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetMaintenanceApiRepositoriesResponses = {
    /**
     * The repositories
     */
    200: Array<RepositoryDto>;
};

export type GetMaintenanceApiRepositoriesResponse = GetMaintenanceApiRepositoriesResponses[keyof GetMaintenanceApiRepositoriesResponses];

export type GetMaintenanceApiRepositoriesByNameData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/maintenance/api/repositories/{name}';
};

export type GetMaintenanceApiRepositoriesByNameErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such repository in the inventory
     */
    404: unknown;
};

export type GetMaintenanceApiRepositoriesByNameResponses = {
    /**
     * The repository
     */
    200: RepositoryDetailDto;
};

export type GetMaintenanceApiRepositoriesByNameResponse = GetMaintenanceApiRepositoriesByNameResponses[keyof GetMaintenanceApiRepositoriesByNameResponses];

export type PostMaintenanceApiRepositoriesByNameBranchesBumpsData = {
    body: TargetedBumpRequest;
    path: {
        name: string;
    };
    query?: never;
    url: '/maintenance/api/repositories/{name}/branches/bumps';
};

export type PostMaintenanceApiRepositoriesByNameBranchesBumpsErrors = {
    /**
     * The branch or a change is not a valid payload
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such repository in the inventory
     */
    404: unknown;
    /**
     * One is already active on that branch, or bumping is disabled
     */
    409: unknown;
};

export type PostMaintenanceApiRepositoriesByNameBranchesBumpsResponses = {
    /**
     * Requested; poll GET /bumps/{id} for resultSha
     */
    202: unknown;
};

export type GetMaintenanceApiRepositoriesByNameDependentsData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/maintenance/api/repositories/{name}/dependents';
};

export type GetMaintenanceApiRepositoriesByNameDependentsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetMaintenanceApiRepositoriesByNameDependentsResponses = {
    /**
     * The dependents, per published artifact
     */
    200: RepositoryDependentsDto;
};

export type GetMaintenanceApiRepositoriesByNameDependentsResponse = GetMaintenanceApiRepositoriesByNameDependentsResponses[keyof GetMaintenanceApiRepositoriesByNameDependentsResponses];

export type GetMaintenanceApiRepositoriesByNameDownstreamData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/maintenance/api/repositories/{name}/downstream';
};

export type GetMaintenanceApiRepositoriesByNameDownstreamErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetMaintenanceApiRepositoriesByNameDownstreamResponses = {
    /**
     * The closure, depth ascending then name
     */
    200: DownstreamDto;
};

export type GetMaintenanceApiRepositoriesByNameDownstreamResponse = GetMaintenanceApiRepositoriesByNameDownstreamResponses[keyof GetMaintenanceApiRepositoriesByNameDownstreamResponses];

export type PostMaintenanceApiRepositoriesByNameGroupsByGroupBumpsData = {
    body?: never;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/maintenance/api/repositories/{name}/groups/{group}/bumps';
};

export type PostMaintenanceApiRepositoriesByNameGroupsByGroupBumpsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such repository, or no such group
     */
    404: unknown;
    /**
     * One is already active, or bumping is disabled
     */
    409: unknown;
};

export type PostMaintenanceApiRepositoriesByNameGroupsByGroupBumpsResponses = {
    /**
     * Requested; poll GET /bumps/{id}
     */
    202: unknown;
};

export type PostMaintenanceApiRepositoriesByNameReleaseRequestsByRequestIdScreenshotBaselinesData = {
    body: BaselinesRequest;
    path: {
        name: string;
        requestId: string;
    };
    query?: never;
    url: '/maintenance/api/repositories/{name}/release-requests/{requestId}/screenshot-baselines';
};

export type PostMaintenanceApiRepositoriesByNameReleaseRequestsByRequestIdScreenshotBaselinesErrors = {
    /**
     * Not a request id, or not a work item
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such repository in the inventory
     */
    404: unknown;
    /**
     * The request takes no branch, one is already running for it, or bumping is disabled
     */
    409: unknown;
};

export type PostMaintenanceApiRepositoriesByNameReleaseRequestsByRequestIdScreenshotBaselinesResponses = {
    /**
     * Requested; poll GET /bumps/{id}
     */
    202: unknown;
};

export type GetMaintenanceApiSbomCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/maintenance/api/sbom-check';
};

export type GetMaintenanceApiSbomCheckErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No check has run yet
     */
    404: unknown;
};

export type GetMaintenanceApiSbomCheckResponses = {
    /**
     * The report
     */
    200: SbomCheckReportDto;
};

export type GetMaintenanceApiSbomCheckResponse = GetMaintenanceApiSbomCheckResponses[keyof GetMaintenanceApiSbomCheckResponses];

export type PostMaintenanceApiSbomCheckRunsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/maintenance/api/sbom-check/runs';
};

export type PostMaintenanceApiSbomCheckRunsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * qits-artifacts could not be asked; nothing stored
     */
    502: unknown;
};

export type PostMaintenanceApiSbomCheckRunsResponses = {
    /**
     * Ran; the body is the report it stored
     */
    202: unknown;
};

export type PostMaintenanceApiScansData = {
    body: StartScanRequest;
    path?: never;
    query?: never;
    url: '/maintenance/api/scans';
};

export type PostMaintenanceApiScansErrors = {
    /**
     * Unknown scope
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostMaintenanceApiScansResponses = {
    /**
     * Queued
     */
    202: unknown;
};

export type GetMaintenanceApiScansByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/maintenance/api/scans/{id}';
};

export type GetMaintenanceApiScansByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such scan
     */
    404: unknown;
};

export type GetMaintenanceApiScansByIdResponses = {
    /**
     * The scan
     */
    200: ScanDto;
};

export type GetMaintenanceApiScansByIdResponse = GetMaintenanceApiScansByIdResponses[keyof GetMaintenanceApiScansByIdResponses];
