// This file is auto-generated by @hey-api/openapi-ts

import { type HttpRequest, httpResource } from '@angular/common/http';

import { client } from '../client.gen';
import type { Options } from '../sdk.gen';
import type { DeleteMaintenanceApiBumpsWindowData, DeleteMaintenanceApiBumpsWindowResponse, GetBumpData, GetBumpResponse, GetBumpWindowData, GetBumpWindowResponse, GetMaintenanceApiAdoptionByReleaseData, GetMaintenanceApiAdoptionByReleaseResponse, GetMaintenanceApiArtifactsData, GetMaintenanceApiArtifactsResponse, GetMaintenanceApiDependenciesData, GetMaintenanceApiDependenciesDependentsData, GetMaintenanceApiDependenciesDependentsResponse, GetMaintenanceApiDependenciesResponse, GetMaintenanceApiPinsData, GetMaintenanceApiPinsResponse, GetMaintenanceApiRepositoriesByNameData, GetMaintenanceApiRepositoriesByNameDependentsData, GetMaintenanceApiRepositoriesByNameDependentsResponse, GetMaintenanceApiRepositoriesByNameDownstreamData, GetMaintenanceApiRepositoriesByNameDownstreamResponse, GetMaintenanceApiRepositoriesByNameResponse, GetMaintenanceApiRepositoriesData, GetMaintenanceApiRepositoriesResponse, GetMaintenanceApiSbomCheckData, GetMaintenanceApiSbomCheckResponse, GetMaintenanceApiScansByIdData, GetMaintenanceApiScansByIdResponse, ListBumpsData, ListBumpsResponse, ListPendingBumpsData, ListPendingBumpsResponse, PostMaintenanceApiArtifactsIngestData, PostMaintenanceApiBumpsWindowData, PostMaintenanceApiBumpsWindowResponse, PostMaintenanceApiRepositoriesByNameBranchesBumpsData, PostMaintenanceApiRepositoriesByNameGroupsByGroupBumpsData, PostMaintenanceApiRepositoriesByNameReleaseRequestsByRequestIdScreenshotBaselinesData, PostMaintenanceApiSbomCheckRunsData, PostMaintenanceApiScansData } from '../types.gen';

/**
 * How far one released repository and version got
 */
export const getMaintenanceApiAdoptionByReleaseRequest = <ThrowOnError extends boolean = false>(options?: Options<GetMaintenanceApiAdoptionByReleaseData, ThrowOnError>): HttpRequest<GetMaintenanceApiAdoptionByReleaseResponse> => (options?.client ?? client).requestOptions<GetMaintenanceApiAdoptionByReleaseResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/adoption/by-release',
    ...options
});

/**
 * Every artifact this platform publishes, with its reach
 */
export const getMaintenanceApiArtifactsRequest = <ThrowOnError extends boolean = false>(options?: Options<GetMaintenanceApiArtifactsData, ThrowOnError>): HttpRequest<GetMaintenanceApiArtifactsResponse> => (options?.client ?? client).requestOptions<GetMaintenanceApiArtifactsResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/artifacts',
    ...options
});

/**
 * Read one released artifact's sbom now
 */
export const postMaintenanceApiArtifactsIngestRequest = <ThrowOnError extends boolean = false>(options: Options<PostMaintenanceApiArtifactsIngestData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'POST',
    url: '/maintenance/api/artifacts/ingest',
    ...options
});

/**
 * The newest bumps, of one repository or of all of them
 */
export const listBumpsRequest = <ThrowOnError extends boolean = false>(options?: Options<ListBumpsData, ThrowOnError>): HttpRequest<ListBumpsResponse> => (options?.client ?? client).requestOptions<ListBumpsResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/bumps',
    ...options
});

/**
 * The newest bumps still on their way
 */
export const listPendingBumpsRequest = <ThrowOnError extends boolean = false>(options?: Options<ListPendingBumpsData, ThrowOnError>): HttpRequest<ListPendingBumpsResponse> => (options?.client ?? client).requestOptions<ListPendingBumpsResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/bumps/pending',
    ...options
});

/**
 * Close the bump dispatch window
 */
export const deleteMaintenanceApiBumpsWindowRequest = <ThrowOnError extends boolean = false>(options?: Options<DeleteMaintenanceApiBumpsWindowData, ThrowOnError>): HttpRequest<DeleteMaintenanceApiBumpsWindowResponse> => (options?.client ?? client).requestOptions<DeleteMaintenanceApiBumpsWindowResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'DELETE',
    url: '/maintenance/api/bumps/window',
    ...options
});

/**
 * The bump dispatch window and everything owed a bump
 */
export const getBumpWindowRequest = <ThrowOnError extends boolean = false>(options?: Options<GetBumpWindowData, ThrowOnError>): HttpRequest<GetBumpWindowResponse> => (options?.client ?? client).requestOptions<GetBumpWindowResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/bumps/window',
    ...options
});

/**
 * Open a bump dispatch window now
 */
export const postMaintenanceApiBumpsWindowRequest = <ThrowOnError extends boolean = false>(options?: Options<PostMaintenanceApiBumpsWindowData, ThrowOnError>): HttpRequest<PostMaintenanceApiBumpsWindowResponse> => (options?.client ?? client).requestOptions<PostMaintenanceApiBumpsWindowResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'POST',
    url: '/maintenance/api/bumps/window',
    ...options
});

/**
 * One bump with the changes it sent
 */
export const getBumpRequest = <ThrowOnError extends boolean = false>(options: Options<GetBumpData, ThrowOnError>): HttpRequest<GetBumpResponse> => (options?.client ?? client).requestOptions<GetBumpResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/bumps/{id}',
    ...options
});

/**
 * Dependencies matching a glob, with every pin of each
 */
export const getMaintenanceApiDependenciesRequest = <ThrowOnError extends boolean = false>(options?: Options<GetMaintenanceApiDependenciesData, ThrowOnError>): HttpRequest<GetMaintenanceApiDependenciesResponse> => (options?.client ?? client).requestOptions<GetMaintenanceApiDependenciesResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/dependencies',
    ...options
});

/**
 * Every released artifact of ours that embeds this dependency
 */
export const getMaintenanceApiDependenciesDependentsRequest = <ThrowOnError extends boolean = false>(options?: Options<GetMaintenanceApiDependenciesDependentsData, ThrowOnError>): HttpRequest<GetMaintenanceApiDependenciesDependentsResponse> => (options?.client ?? client).requestOptions<GetMaintenanceApiDependenciesDependentsResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/dependencies/dependents',
    ...options
});

/**
 * Every internal artifact version the platform's manifests still pin
 */
export const getMaintenanceApiPinsRequest = <ThrowOnError extends boolean = false>(options?: Options<GetMaintenanceApiPinsData, ThrowOnError>): HttpRequest<GetMaintenanceApiPinsResponse> => (options?.client ?? client).requestOptions<GetMaintenanceApiPinsResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/pins',
    ...options
});

/**
 * Every repository in the inventory, with its groups and what is pending
 */
export const getMaintenanceApiRepositoriesRequest = <ThrowOnError extends boolean = false>(options?: Options<GetMaintenanceApiRepositoriesData, ThrowOnError>): HttpRequest<GetMaintenanceApiRepositoriesResponse> => (options?.client ?? client).requestOptions<GetMaintenanceApiRepositoriesResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/repositories',
    ...options
});

/**
 * One repository with every pin it holds
 */
export const getMaintenanceApiRepositoriesByNameRequest = <ThrowOnError extends boolean = false>(options: Options<GetMaintenanceApiRepositoriesByNameData, ThrowOnError>): HttpRequest<GetMaintenanceApiRepositoriesByNameResponse> => (options?.client ?? client).requestOptions<GetMaintenanceApiRepositoriesByNameResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/repositories/{name}',
    ...options
});

/**
 * Write the named changes onto a branch the caller owns
 */
export const postMaintenanceApiRepositoriesByNameBranchesBumpsRequest = <ThrowOnError extends boolean = false>(options: Options<PostMaintenanceApiRepositoriesByNameBranchesBumpsData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'POST',
    url: '/maintenance/api/repositories/{name}/branches/bumps',
    ...options
});

/**
 * Who embeds the artifacts this repository publishes
 */
export const getMaintenanceApiRepositoriesByNameDependentsRequest = <ThrowOnError extends boolean = false>(options: Options<GetMaintenanceApiRepositoriesByNameDependentsData, ThrowOnError>): HttpRequest<GetMaintenanceApiRepositoriesByNameDependentsResponse> => (options?.client ?? client).requestOptions<GetMaintenanceApiRepositoriesByNameDependentsResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/repositories/{name}/dependents',
    ...options
});

/**
 * Everything downstream of this repository, ordered upstream first
 */
export const getMaintenanceApiRepositoriesByNameDownstreamRequest = <ThrowOnError extends boolean = false>(options: Options<GetMaintenanceApiRepositoriesByNameDownstreamData, ThrowOnError>): HttpRequest<GetMaintenanceApiRepositoriesByNameDownstreamResponse> => (options?.client ?? client).requestOptions<GetMaintenanceApiRepositoriesByNameDownstreamResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/repositories/{name}/downstream',
    ...options
});

/**
 * Put this group's pending changes on its maintenance branch
 */
export const postMaintenanceApiRepositoriesByNameGroupsByGroupBumpsRequest = <ThrowOnError extends boolean = false>(options: Options<PostMaintenanceApiRepositoriesByNameGroupsByGroupBumpsData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'POST',
    url: '/maintenance/api/repositories/{name}/groups/{group}/bumps',
    ...options
});

/**
 * Update a release request's screenshot baselines in the CI image
 */
export const postMaintenanceApiRepositoriesByNameReleaseRequestsByRequestIdScreenshotBaselinesRequest = <ThrowOnError extends boolean = false>(options: Options<PostMaintenanceApiRepositoriesByNameReleaseRequestsByRequestIdScreenshotBaselinesData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'POST',
    url: '/maintenance/api/repositories/{name}/release-requests/{requestId}/screenshot-baselines',
    ...options
});

/**
 * The last SBOM check's report
 */
export const getMaintenanceApiSbomCheckRequest = <ThrowOnError extends boolean = false>(options?: Options<GetMaintenanceApiSbomCheckData, ThrowOnError>): HttpRequest<GetMaintenanceApiSbomCheckResponse> => (options?.client ?? client).requestOptions<GetMaintenanceApiSbomCheckResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/sbom-check',
    ...options
});

/**
 * Run the SBOM check now
 */
export const postMaintenanceApiSbomCheckRunsRequest = <ThrowOnError extends boolean = false>(options?: Options<PostMaintenanceApiSbomCheckRunsData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'POST',
    url: '/maintenance/api/sbom-check/runs',
    ...options
});

/**
 * Re-scan the manifests and refresh the latest versions
 */
export const postMaintenanceApiScansRequest = <ThrowOnError extends boolean = false>(options: Options<PostMaintenanceApiScansData, ThrowOnError>): HttpRequest<unknown> => (options?.client ?? client).requestOptions<unknown, ThrowOnError>({
    responseStyle: 'data',
    method: 'POST',
    url: '/maintenance/api/scans',
    ...options
});

/**
 * One scan and its status
 */
export const getMaintenanceApiScansByIdRequest = <ThrowOnError extends boolean = false>(options: Options<GetMaintenanceApiScansByIdData, ThrowOnError>): HttpRequest<GetMaintenanceApiScansByIdResponse> => (options?.client ?? client).requestOptions<GetMaintenanceApiScansByIdResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/maintenance/api/scans/{id}',
    ...options
});

/**
 * How far one released repository and version got
 */
export const getMaintenanceApiAdoptionByReleaseResource = <ThrowOnError extends boolean = false>(options?: () => Options<GetMaintenanceApiAdoptionByReleaseData, ThrowOnError> | undefined) => httpResource<GetMaintenanceApiAdoptionByReleaseResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getMaintenanceApiAdoptionByReleaseRequest(opts) : undefined;
});

/**
 * Every artifact this platform publishes, with its reach
 */
export const getMaintenanceApiArtifactsResource = <ThrowOnError extends boolean = false>(options?: () => Options<GetMaintenanceApiArtifactsData, ThrowOnError> | undefined) => httpResource<GetMaintenanceApiArtifactsResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getMaintenanceApiArtifactsRequest(opts) : undefined;
});

/**
 * Read one released artifact's sbom now
 */
export const postMaintenanceApiArtifactsIngestResource = <ThrowOnError extends boolean = false>(options: () => Options<PostMaintenanceApiArtifactsIngestData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? postMaintenanceApiArtifactsIngestRequest(opts) : undefined;
});

/**
 * The newest bumps, of one repository or of all of them
 */
export const listBumpsResource = <ThrowOnError extends boolean = false>(options?: () => Options<ListBumpsData, ThrowOnError> | undefined) => httpResource<ListBumpsResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? listBumpsRequest(opts) : undefined;
});

/**
 * The newest bumps still on their way
 */
export const listPendingBumpsResource = <ThrowOnError extends boolean = false>(options?: () => Options<ListPendingBumpsData, ThrowOnError> | undefined) => httpResource<ListPendingBumpsResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? listPendingBumpsRequest(opts) : undefined;
});

/**
 * Close the bump dispatch window
 */
export const deleteMaintenanceApiBumpsWindowResource = <ThrowOnError extends boolean = false>(options?: () => Options<DeleteMaintenanceApiBumpsWindowData, ThrowOnError> | undefined) => httpResource<DeleteMaintenanceApiBumpsWindowResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? deleteMaintenanceApiBumpsWindowRequest(opts) : undefined;
});

/**
 * The bump dispatch window and everything owed a bump
 */
export const getBumpWindowResource = <ThrowOnError extends boolean = false>(options?: () => Options<GetBumpWindowData, ThrowOnError> | undefined) => httpResource<GetBumpWindowResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getBumpWindowRequest(opts) : undefined;
});

/**
 * Open a bump dispatch window now
 */
export const postMaintenanceApiBumpsWindowResource = <ThrowOnError extends boolean = false>(options?: () => Options<PostMaintenanceApiBumpsWindowData, ThrowOnError> | undefined) => httpResource<PostMaintenanceApiBumpsWindowResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? postMaintenanceApiBumpsWindowRequest(opts) : undefined;
});

/**
 * One bump with the changes it sent
 */
export const getBumpResource = <ThrowOnError extends boolean = false>(options: () => Options<GetBumpData, ThrowOnError> | undefined) => httpResource<GetBumpResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getBumpRequest(opts) : undefined;
});

/**
 * Dependencies matching a glob, with every pin of each
 */
export const getMaintenanceApiDependenciesResource = <ThrowOnError extends boolean = false>(options?: () => Options<GetMaintenanceApiDependenciesData, ThrowOnError> | undefined) => httpResource<GetMaintenanceApiDependenciesResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getMaintenanceApiDependenciesRequest(opts) : undefined;
});

/**
 * Every released artifact of ours that embeds this dependency
 */
export const getMaintenanceApiDependenciesDependentsResource = <ThrowOnError extends boolean = false>(options?: () => Options<GetMaintenanceApiDependenciesDependentsData, ThrowOnError> | undefined) => httpResource<GetMaintenanceApiDependenciesDependentsResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getMaintenanceApiDependenciesDependentsRequest(opts) : undefined;
});

/**
 * Every internal artifact version the platform's manifests still pin
 */
export const getMaintenanceApiPinsResource = <ThrowOnError extends boolean = false>(options?: () => Options<GetMaintenanceApiPinsData, ThrowOnError> | undefined) => httpResource<GetMaintenanceApiPinsResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getMaintenanceApiPinsRequest(opts) : undefined;
});

/**
 * Every repository in the inventory, with its groups and what is pending
 */
export const getMaintenanceApiRepositoriesResource = <ThrowOnError extends boolean = false>(options?: () => Options<GetMaintenanceApiRepositoriesData, ThrowOnError> | undefined) => httpResource<GetMaintenanceApiRepositoriesResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getMaintenanceApiRepositoriesRequest(opts) : undefined;
});

/**
 * One repository with every pin it holds
 */
export const getMaintenanceApiRepositoriesByNameResource = <ThrowOnError extends boolean = false>(options: () => Options<GetMaintenanceApiRepositoriesByNameData, ThrowOnError> | undefined) => httpResource<GetMaintenanceApiRepositoriesByNameResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getMaintenanceApiRepositoriesByNameRequest(opts) : undefined;
});

/**
 * Write the named changes onto a branch the caller owns
 */
export const postMaintenanceApiRepositoriesByNameBranchesBumpsResource = <ThrowOnError extends boolean = false>(options: () => Options<PostMaintenanceApiRepositoriesByNameBranchesBumpsData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? postMaintenanceApiRepositoriesByNameBranchesBumpsRequest(opts) : undefined;
});

/**
 * Who embeds the artifacts this repository publishes
 */
export const getMaintenanceApiRepositoriesByNameDependentsResource = <ThrowOnError extends boolean = false>(options: () => Options<GetMaintenanceApiRepositoriesByNameDependentsData, ThrowOnError> | undefined) => httpResource<GetMaintenanceApiRepositoriesByNameDependentsResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getMaintenanceApiRepositoriesByNameDependentsRequest(opts) : undefined;
});

/**
 * Everything downstream of this repository, ordered upstream first
 */
export const getMaintenanceApiRepositoriesByNameDownstreamResource = <ThrowOnError extends boolean = false>(options: () => Options<GetMaintenanceApiRepositoriesByNameDownstreamData, ThrowOnError> | undefined) => httpResource<GetMaintenanceApiRepositoriesByNameDownstreamResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getMaintenanceApiRepositoriesByNameDownstreamRequest(opts) : undefined;
});

/**
 * Put this group's pending changes on its maintenance branch
 */
export const postMaintenanceApiRepositoriesByNameGroupsByGroupBumpsResource = <ThrowOnError extends boolean = false>(options: () => Options<PostMaintenanceApiRepositoriesByNameGroupsByGroupBumpsData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? postMaintenanceApiRepositoriesByNameGroupsByGroupBumpsRequest(opts) : undefined;
});

/**
 * Update a release request's screenshot baselines in the CI image
 */
export const postMaintenanceApiRepositoriesByNameReleaseRequestsByRequestIdScreenshotBaselinesResource = <ThrowOnError extends boolean = false>(options: () => Options<PostMaintenanceApiRepositoriesByNameReleaseRequestsByRequestIdScreenshotBaselinesData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? postMaintenanceApiRepositoriesByNameReleaseRequestsByRequestIdScreenshotBaselinesRequest(opts) : undefined;
});

/**
 * The last SBOM check's report
 */
export const getMaintenanceApiSbomCheckResource = <ThrowOnError extends boolean = false>(options?: () => Options<GetMaintenanceApiSbomCheckData, ThrowOnError> | undefined) => httpResource<GetMaintenanceApiSbomCheckResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getMaintenanceApiSbomCheckRequest(opts) : undefined;
});

/**
 * Run the SBOM check now
 */
export const postMaintenanceApiSbomCheckRunsResource = <ThrowOnError extends boolean = false>(options?: () => Options<PostMaintenanceApiSbomCheckRunsData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? postMaintenanceApiSbomCheckRunsRequest(opts) : undefined;
});

/**
 * Re-scan the manifests and refresh the latest versions
 */
export const postMaintenanceApiScansResource = <ThrowOnError extends boolean = false>(options: () => Options<PostMaintenanceApiScansData, ThrowOnError> | undefined) => httpResource<unknown>(() => {
    const opts = options ? options() : undefined;
    return opts ? postMaintenanceApiScansRequest(opts) : undefined;
});

/**
 * One scan and its status
 */
export const getMaintenanceApiScansByIdResource = <ThrowOnError extends boolean = false>(options: () => Options<GetMaintenanceApiScansByIdData, ThrowOnError> | undefined) => httpResource<GetMaintenanceApiScansByIdResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? getMaintenanceApiScansByIdRequest(opts) : undefined;
});
