// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Baseline = {
    runId?: string;
    version?: string;
};

export type Blocker = {
    runId?: string;
    repoName?: string;
};

export type CancelReleaseRequestRunsRequest = {
    /**
     * The repository whose runs to stop
     */
    repoId: string;
    /**
     * The release request whose work is withdrawn
     */
    releaseRequestId: string;
};

export type CancelReleaseRequestRunsResponse = {
    runIds?: Array<string>;
};

export type CancelRunRequest = {
    reason?: string;
};

export type CiBaselineAnswer = {
    baseline?: CiReportBaselineDto;
};

export type CiLiveStepDto = {
    stepIndex?: number;
    startedAt?: Instant;
    output?: string;
};

export type CiReportBaselineDto = {
    version?: string;
    runId?: string;
    releaseRequestId?: string;
    tagSha?: string;
};

export type CiReportDto = {
    id?: string;
    kind?: string;
    kindVersion?: number;
    stepIndex?: number;
    highlights?: Array<CiReportHighlightDto>;
    baselineRunId?: string;
    baselineVersion?: string;
    payloadBytes?: number;
    submittedAt?: Instant;
    payload?: JsonNode;
};

export type CiReportHighlightDto = {
    severity?: string;
    text?: string;
    metric?: string;
    value?: number;
    delta?: number;
};

export type CiReportSubmission = {
    kindVersion?: number;
    highlights?: Array<CiReportHighlightDto>;
    baseline?: Baseline;
    payload?: JsonNode;
};

export type CiReportSummaryDto = {
    id?: string;
    kind?: string;
    kindVersion?: number;
    stepIndex?: number;
    highlights?: Array<CiReportHighlightDto>;
    baselineRunId?: string;
    baselineVersion?: string;
    payloadBytes?: number;
    submittedAt?: Instant;
};

export type CiRunDto = {
    id?: string;
    repoId?: string;
    projectId?: string;
    repoName?: string;
    branch?: string;
    commitSha?: string;
    status?: CiRunStatus;
    createdAt?: Instant;
    startedAt?: Instant;
    finishedAt?: Instant;
    cancellationReason?: string;
    supersededByRunId?: string;
    daemonVersion?: string;
    triggerType?: CiTriggerType;
    triggerEventId?: string;
    triggerEventName?: string;
    releaseRequestId?: string;
    retryOfRunId?: string;
    configPath?: string;
    archetypeName?: string;
    archetypeConfigPath?: string;
    archetypeRev?: string;
    archetypeVersion?: string;
    priority?: string;
    expectedStepDurationsMillis?: Array<number>;
    steps?: Array<CiStepDto>;
    live?: CiLiveStepDto;
    phase?: CiRunPhase;
    queuePosition?: number;
    expectedStartInMillis?: number;
    expectedFinishInMillis?: number;
    predictionUnavailable?: string;
    ordering?: CiRunOrderingDto;
    runnerId?: Uuid;
    runnerName?: string;
    retryReason?: string;
    autoRetry?: boolean;
};

export type CiRunOrderingDto = {
    position?: number;
    kindTier?: number;
    priority?: string;
    priorityRank?: number;
    topologyBlockers?: Array<Blocker>;
    selection?: Selection;
};

export type CiRunPhase = 'RELEASE_REQUEST' | 'RELEASE';

export type CiRunReportsDto = {
    runId?: string;
    commitSha?: string;
    releaseRequestId?: string;
    baseline?: CiReportBaselineDto;
    reports?: Array<CiReportSummaryDto>;
};

export type CiRunStatus = 'QUEUED' | 'RUNNING' | 'SUCCESS' | 'FAILED' | 'CANCELLED' | 'CONFIG_ERROR' | 'TIMED_OUT';

export type CiRunnerCreated = {
    id?: Uuid;
    name?: string;
    description?: string;
    slots?: number;
    plane?: CiRunnerPlane;
    stepMemoryLimit?: string;
    capabilities?: JsonNode;
    registered?: boolean;
    connected?: boolean;
    heldRuns?: number;
    lastSeenAt?: Instant;
    createdAt?: Instant;
    runnerVersion?: string;
    targetVersion?: string;
    updating?: boolean;
    quarantined?: boolean;
    quarantineReason?: string;
    quarantinedAt?: Instant;
    lastHealthcheck?: CiRunnerHealthcheckDto;
    /**
     * The one line that installs this runner on a host: it fetches the generic install script with the registration token and pipes it into sudo sh with this runner's values. Returned once; never readable again
     */
    installScript?: string;
};

export type CiRunnerDto = {
    id?: Uuid;
    name?: string;
    description?: string;
    slots?: number;
    plane?: CiRunnerPlane;
    stepMemoryLimit?: string;
    capabilities?: JsonNode;
    registered?: boolean;
    connected?: boolean;
    heldRuns?: number;
    lastSeenAt?: Instant;
    createdAt?: Instant;
    runnerVersion?: string;
    targetVersion?: string;
    updating?: boolean;
    quarantined?: boolean;
    quarantineReason?: string;
    quarantinedAt?: Instant;
    lastHealthcheck?: CiRunnerHealthcheckDto;
};

export type CiRunnerHealthcheckDto = {
    at?: Instant;
    result?: string;
    runId?: string;
    detail?: string;
};

export type CiRunnerPlane = 'EDGE';

export type CiStepDto = {
    stepIndex?: number;
    image?: string;
    status?: CiStepStatus;
    exitCode?: number;
    startedAt?: Instant;
    finishedAt?: Instant;
    output?: string;
};

export type CiStepStatus = 'PENDING' | 'RUNNING' | 'SUCCESS' | 'FAILED' | 'SKIPPED' | 'TIMED_OUT';

export type CiTriggerType = 'POST_RECEIVE' | 'EVENT';

export type CreateRunnerRequest = {
    /**
     * [a-z][a-z0-9-]{0,63}, unique
     */
    name: string;
    /**
     * Free text, at most 1024 characters
     */
    description?: string;
    /**
     * How many steps it may hold at once; 0 drains it. Default 1
     */
    slots?: number;
    /**
     * Where its steps reach the platform. There is one plane, EDGE — through the public names — and absent means EDGE. Any other value is refused 400
     */
    plane?: 'EDGE';
    /**
     * The memory cap its step containers get, memory and memory-swap alike: a docker size, digits and an optional b, k, m or g (6g, 6144m), at least 6m. Absent or blank is the platform default, qits.ci.memory-limit
     */
    stepMemoryLimit?: string;
};

export type DaemonPinDto = {
    daemonName?: string;
    daemonVersion?: string;
    previousDaemonVersion?: string;
    source?: string;
};

export type HealthCheckQueued = {
    runId?: string;
};

export type Instant = string;

export type JsonNode = {
    empty?: boolean;
    valueNode?: boolean;
    containerNode?: boolean;
    missingNode?: boolean;
    array?: boolean;
    object?: boolean;
    nodeType?: JsonNodeType;
    pojo?: boolean;
    number?: boolean;
    integralNumber?: boolean;
    floatingPointNumber?: boolean;
    short?: boolean;
    int?: boolean;
    long?: boolean;
    float?: boolean;
    double?: boolean;
    bigDecimal?: boolean;
    bigInteger?: boolean;
    textual?: boolean;
    boolean?: boolean;
    null?: boolean;
    binary?: boolean;
};

export type JsonNodeType = 'ARRAY' | 'BINARY' | 'BOOLEAN' | 'MISSING' | 'NULL' | 'NUMBER' | 'OBJECT' | 'POJO' | 'STRING';

export type ListRepositoryIdsResponse = {
    repositoryIds?: Array<string>;
};

export type ListRepositorySummariesResponse = {
    repositories?: Array<RepositorySummaryDto>;
};

export type ListRunnersResponse = {
    runners?: Array<CiRunnerDto>;
};

export type ListRunsResponse = {
    runs?: Array<CiRunDto>;
};

export type PatchRunnerRequest = {
    /**
     * 0 drains the runner; absent leaves it
     */
    slots?: number;
    /**
     * Blank clears it; absent leaves it
     */
    description?: string;
    /**
     * EDGE, or absent; it changes nothing. Any other value is refused 400
     */
    plane?: 'EDGE';
    /**
     * A docker size (6g, 6144m) its step containers are capped at; blank clears it back to the platform default, qits.ci.memory-limit; absent leaves it. Reaches the runner's next step
     */
    stepMemoryLimit?: string;
};

export type QueueResponse = {
    generatedAt?: Instant;
    running?: Array<CiRunDto>;
    queued?: Array<CiRunDto>;
    runners?: Array<RunnerCapacity>;
};

export type RegisterRunnerRequest = {
    /**
     * What the runner says about itself — a JSON object, at most 16 KiB
     */
    capabilities?: JsonNode;
};

export type RegisteredRunner = {
    clientId?: string;
    secret?: string;
    tokenUrl?: string;
    audience?: string;
    socketUrl?: string;
};

export type ReleaseArtifactsResponse = {
    repository?: string;
    version?: string;
    artifacts?: Array<ReleasedArtifact>;
};

export type ReleasePhaseResponse = {
    repositoryId?: string;
    rev?: string;
    declared?: boolean;
    detail?: string;
};

export type ReleasedArtifact = {
    type?: string;
    name?: string;
    publish?: string;
    decision?: string;
    unchangedSince?: string;
    runId?: string;
    decidedAt?: Instant;
};

export type RepositorySummaryDto = {
    repositoryId?: string;
    projectId?: string;
    repoName?: string;
    lastRun?: CiRunDto;
    lastMainRun?: CiRunDto;
};

export type RerunReleaseRequestPhaseRequest = {
    /**
     * The repository whose run to re-fire
     */
    repoId: string;
    /**
     * The release request the run serves
     */
    releaseRequestId: string;
    /**
     * Which phase of the release to re-fire: RELEASE_REQUEST (QA) or RELEASE (publish)
     */
    phase: 'RELEASE_REQUEST' | 'RELEASE';
};

export type RetryRunResponse = {
    runId?: string;
};

export type RunnerCapacity = {
    id?: Uuid;
    name?: string;
    slots?: number;
    held?: number;
    connected?: boolean;
    runnerVersion?: string;
    targetVersion?: string;
    updating?: boolean;
    quarantined?: boolean;
    quarantineReason?: string;
    quarantinedAt?: Instant;
    lastHealthcheck?: CiRunnerHealthcheckDto;
};

export type Selection = 'UNBLOCKED' | 'CYCLE_DEGRADED';

export type TriggerEventRequest = {
    /**
     * The event signature, matched against a trigger file's `event:`
     */
    name?: string;
    /**
     * The event payload, exactly as it would arrive off the bus
     */
    payload?: {
        [key: string]: unknown;
    };
    /**
     * ISO-8601 instant. Absent: now.
     */
    occurredAt?: string;
    /**
     * UUID. Absent: a fresh random one — see the dedupe note.
     */
    eventId?: string;
};

export type TriggerEventResult = {
    eventId?: string;
    runIds?: Array<string>;
    repositoriesRead?: number;
    repositoriesSkipped?: Array<string>;
};

export type Uuid = string;

export type GetCiApiDaemonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ci/api/daemon';
};

export type GetCiApiDaemonErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetCiApiDaemonResponses = {
    /**
     * The pinned daemon binary. daemonVersion is the version of the protocol dependency this service is built against, with source "pinned"; source is "override" when a deployment has set qits.ci.daemon-version-override. previousDaemonVersion is always blank: a pin has no fallback rung.
     */
    200: DaemonPinDto;
};

export type GetCiApiDaemonResponse = GetCiApiDaemonResponses[keyof GetCiApiDaemonResponses];

export type PostCiApiEventsTriggerData = {
    body: TriggerEventRequest;
    path?: never;
    query?: never;
    url: '/ci/api/events/trigger';
};

export type PostCiApiEventsTriggerErrors = {
    /**
     * Blank name, missing payload, or an unparseable timestamp or id
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * The token covers no repository here — its project claim names a project this instance can place no repository in
     */
    403: unknown;
    /**
     * Not evaluated — no candidate repository could be read. Retry.
     */
    503: TriggerEventResult;
};

export type PostCiApiEventsTriggerError = PostCiApiEventsTriggerErrors[keyof PostCiApiEventsTriggerErrors];

export type PostCiApiEventsTriggerResponses = {
    /**
     * Evaluated, with the runs it recorded and which repositories it could ask
     */
    200: TriggerEventResult;
};

export type PostCiApiEventsTriggerResponse = PostCiApiEventsTriggerResponses[keyof PostCiApiEventsTriggerResponses];

export type GetCiApiRepositoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ci/api/repositories';
};

export type GetCiApiRepositoriesErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetCiApiRepositoriesResponses = {
    /**
     * Distinct repository ids, ascending
     */
    200: ListRepositoryIdsResponse;
};

export type GetCiApiRepositoriesResponse = GetCiApiRepositoriesResponses[keyof GetCiApiRepositoriesResponses];

export type GetCiApiRepositoriesSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ci/api/repositories/summary';
};

export type GetCiApiRepositoriesSummaryErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetCiApiRepositoriesSummaryResponses = {
    /**
     * One entry per repository, ascending by id
     */
    200: ListRepositorySummariesResponse;
};

export type GetCiApiRepositoriesSummaryResponse = GetCiApiRepositoriesSummaryResponses[keyof GetCiApiRepositoriesSummaryResponses];

export type GetCiApiRepositoriesByRepoIdReleasePhaseData = {
    body?: never;
    path: {
        repoId: string;
    };
    query: {
        /**
         * A git rev the host can resolve, in practice refs/tags/<version>
         */
        rev: string;
    };
    url: '/ci/api/repositories/{repoId}/release-phase';
};

export type GetCiApiRepositoriesByRepoIdReleasePhaseErrors = {
    /**
     * Missing or blank rev
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * Not answered — the repository is in no catalogue here, or the slot file or its archetype could not be read. Retry.
     */
    503: unknown;
};

export type GetCiApiRepositoriesByRepoIdReleasePhaseResponses = {
    /**
     * Answered — declared true or false, with the reason
     */
    200: ReleasePhaseResponse;
};

export type GetCiApiRepositoriesByRepoIdReleasePhaseResponse = GetCiApiRepositoriesByRepoIdReleasePhaseResponses[keyof GetCiApiRepositoriesByRepoIdReleasePhaseResponses];

export type GetCiApiRepositoriesByRepoIdReleasesByVersionArtifactsData = {
    body?: never;
    path: {
        repoId: string;
        version: string;
    };
    query?: never;
    url: '/ci/api/repositories/{repoId}/releases/{version}/artifacts';
};

export type GetCiApiRepositoriesByRepoIdReleasesByVersionArtifactsErrors = {
    /**
     * Blank version
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetCiApiRepositoriesByRepoIdReleasesByVersionArtifactsResponses = {
    /**
     * The decision record, one entry per artifact; empty when nothing was owed
     */
    200: ReleaseArtifactsResponse;
};

export type GetCiApiRepositoriesByRepoIdReleasesByVersionArtifactsResponse = GetCiApiRepositoriesByRepoIdReleasesByVersionArtifactsResponses[keyof GetCiApiRepositoriesByRepoIdReleasesByVersionArtifactsResponses];

export type GetCiApiRunnersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ci/api/runners';
};

export type GetCiApiRunnersErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetCiApiRunnersResponses = {
    /**
     * Every runner, by name
     */
    200: ListRunnersResponse;
};

export type GetCiApiRunnersResponse = GetCiApiRunnersResponses[keyof GetCiApiRunnersResponses];

export type PostCiApiRunnersData = {
    body: CreateRunnerRequest;
    path?: never;
    query?: never;
    url: '/ci/api/runners';
};

export type PostCiApiRunnersErrors = {
    /**
     * A malformed name, slots, description or stepMemoryLimit, or UNKNOWN_PLANE: a plane other than EDGE — INTERNAL included, which no longer exists
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * The name is taken
     */
    409: unknown;
    /**
     * qits-idp refused the registration token
     */
    502: unknown;
    /**
     * This deployment commissions nothing, or cannot render an install script — which includes knowing no public domain to address a runner by
     */
    503: unknown;
};

export type PostCiApiRunnersResponses = {
    /**
     * The runner and the install line carrying its registration token
     */
    201: CiRunnerCreated;
};

export type PostCiApiRunnersResponse = PostCiApiRunnersResponses[keyof PostCiApiRunnersResponses];

export type GetCiApiRunnersInstallShData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ci/api/runners/install.sh';
};

export type GetCiApiRunnersInstallShErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * This deployment cannot render an install script
     */
    503: unknown;
};

export type GetCiApiRunnersInstallShResponses = {
    /**
     * A POSIX sh script, carrying no secret
     */
    200: string;
};

export type GetCiApiRunnersInstallShResponse = GetCiApiRunnersInstallShResponses[keyof GetCiApiRunnersInstallShResponses];

export type DeleteCiApiRunnersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/ci/api/runners/{id}';
};

export type DeleteCiApiRunnersByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such runner
     */
    404: unknown;
    /**
     * The runner holds a running run, or LAST_RUNNER: it is localhost and no other runner exists
     */
    409: unknown;
};

export type DeleteCiApiRunnersByIdResponses = {
    /**
     * Gone
     */
    204: void;
};

export type DeleteCiApiRunnersByIdResponse = DeleteCiApiRunnersByIdResponses[keyof DeleteCiApiRunnersByIdResponses];

export type GetCiApiRunnersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/ci/api/runners/{id}';
};

export type GetCiApiRunnersByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such runner
     */
    404: unknown;
};

export type GetCiApiRunnersByIdResponses = {
    /**
     * The runner
     */
    200: CiRunnerDto;
};

export type GetCiApiRunnersByIdResponse = GetCiApiRunnersByIdResponses[keyof GetCiApiRunnersByIdResponses];

export type PatchCiApiRunnersByIdData = {
    body: PatchRunnerRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/ci/api/runners/{id}';
};

export type PatchCiApiRunnersByIdErrors = {
    /**
     * Negative slots, an overlong description, a malformed stepMemoryLimit, or UNKNOWN_PLANE: a plane other than EDGE
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such runner
     */
    404: unknown;
};

export type PatchCiApiRunnersByIdResponses = {
    /**
     * The runner as it now is
     */
    200: CiRunnerDto;
};

export type PatchCiApiRunnersByIdResponse = PatchCiApiRunnersByIdResponses[keyof PatchCiApiRunnersByIdResponses];

export type PostCiApiRunnersByIdGreenlightData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/ci/api/runners/{id}/greenlight';
};

export type PostCiApiRunnersByIdGreenlightErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such runner
     */
    404: unknown;
};

export type PostCiApiRunnersByIdGreenlightResponses = {
    /**
     * The runner as it now is
     */
    200: CiRunnerDto;
};

export type PostCiApiRunnersByIdGreenlightResponse = PostCiApiRunnersByIdGreenlightResponses[keyof PostCiApiRunnersByIdGreenlightResponses];

export type PostCiApiRunnersByIdHealthcheckData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/ci/api/runners/{id}/healthcheck';
};

export type PostCiApiRunnersByIdHealthcheckErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such runner
     */
    404: unknown;
    /**
     * One is already queued or running for it
     */
    409: unknown;
    /**
     * The health check's repository, its head or its image could not be resolved; ask again
     */
    503: unknown;
};

export type PostCiApiRunnersByIdHealthcheckResponses = {
    /**
     * The health check's run id
     */
    202: HealthCheckQueued;
};

export type PostCiApiRunnersByIdHealthcheckResponse = PostCiApiRunnersByIdHealthcheckResponses[keyof PostCiApiRunnersByIdHealthcheckResponses];

export type PostCiApiRunnersByIdRegisterData = {
    body: RegisterRunnerRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/ci/api/runners/{id}/register';
};

export type PostCiApiRunnersByIdRegisterErrors = {
    /**
     * Capabilities that are not a JSON object
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * The token is not this runner's
     */
    403: unknown;
    /**
     * No such runner
     */
    404: unknown;
    /**
     * The runner is already registered
     */
    409: unknown;
    /**
     * qits-idp refused the runner's client
     */
    502: unknown;
    /**
     * This deployment commissions nothing, or knows no public domain to tell the runner its addresses by
     */
    503: unknown;
};

export type PostCiApiRunnersByIdRegisterResponses = {
    /**
     * The runner's own client and where to use it
     */
    200: RegisteredRunner;
};

export type PostCiApiRunnersByIdRegisterResponse = PostCiApiRunnersByIdRegisterResponses[keyof PostCiApiRunnersByIdRegisterResponses];

export type PostCiApiRunnersByIdRegistrationTokenData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/ci/api/runners/{id}/registration-token';
};

export type PostCiApiRunnersByIdRegistrationTokenErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such runner
     */
    404: unknown;
    /**
     * The runner is already registered
     */
    409: unknown;
    /**
     * qits-idp refused the registration token
     */
    502: unknown;
    /**
     * This deployment commissions nothing, or cannot render an install script
     */
    503: unknown;
};

export type PostCiApiRunnersByIdRegistrationTokenResponses = {
    /**
     * The runner and the install line carrying its new registration token
     */
    200: CiRunnerCreated;
};

export type PostCiApiRunnersByIdRegistrationTokenResponse = PostCiApiRunnersByIdRegistrationTokenResponses[keyof PostCiApiRunnersByIdRegistrationTokenResponses];

export type GetCiApiRunsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Return only the newest n runs; omit for all of them
         */
        limit?: number;
        /**
         * The repository whose runs to list — required
         */
        repositoryId: string;
    };
    url: '/ci/api/runs';
};

export type GetCiApiRunsErrors = {
    /**
     * The repository id is missing or invalid, or the limit is not a positive integer
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetCiApiRunsResponses = {
    /**
     * The repository's runs with their step boundaries, without step output
     */
    200: ListRunsResponse;
};

export type GetCiApiRunsResponse = GetCiApiRunsResponses[keyof GetCiApiRunsResponses];

export type GetCiApiRunsActiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ci/api/runs/active';
};

export type GetCiApiRunsActiveErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetCiApiRunsActiveResponses = {
    /**
     * The active runs with their step boundaries and queue position, without step output
     */
    200: ListRunsResponse;
};

export type GetCiApiRunsActiveResponse = GetCiApiRunsActiveResponses[keyof GetCiApiRunsActiveResponses];

export type PostCiApiRunsCancellationsData = {
    body: CancelReleaseRequestRunsRequest;
    path?: never;
    query?: never;
    url: '/ci/api/runs/cancellations';
};

export type PostCiApiRunsCancellationsErrors = {
    /**
     * The repository id or the release request id is missing or invalid
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * The token covers this repository for nobody — no project claim and no platform-wide role, or a project claim this instance cannot place the repository in
     */
    403: unknown;
};

export type PostCiApiRunsCancellationsResponses = {
    /**
     * The request's runs have been stopped or asked to stop
     */
    202: CancelReleaseRequestRunsResponse;
};

export type PostCiApiRunsCancellationsResponse = PostCiApiRunsCancellationsResponses[keyof PostCiApiRunsCancellationsResponses];

export type GetCiApiRunsFinishedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return the newest n finished runs; omit for 5, capped at 100
         */
        limit?: number;
    };
    url: '/ci/api/runs/finished';
};

export type GetCiApiRunsFinishedErrors = {
    /**
     * The limit is not a positive integer
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetCiApiRunsFinishedResponses = {
    /**
     * The finished runs with their step boundaries, without step output
     */
    200: ListRunsResponse;
};

export type GetCiApiRunsFinishedResponse = GetCiApiRunsFinishedResponses[keyof GetCiApiRunsFinishedResponses];

export type GetCiApiRunsQueueData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ci/api/runs/queue';
};

export type GetCiApiRunsQueueErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetCiApiRunsQueueResponses = {
    /**
     * The queue at one instant
     */
    200: QueueResponse;
};

export type GetCiApiRunsQueueResponse = GetCiApiRunsQueueResponses[keyof GetCiApiRunsQueueResponses];

export type PostCiApiRunsRerunData = {
    body: RerunReleaseRequestPhaseRequest;
    path?: never;
    query?: never;
    url: '/ci/api/runs/rerun';
};

export type PostCiApiRunsRerunErrors = {
    /**
     * The repository id, the release request id or the phase is missing or invalid
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * The token covers this repository for nobody — no project claim and no platform-wide role, or a project claim this instance cannot place the repository in
     */
    403: unknown;
    /**
     * No such repository
     */
    404: unknown;
    /**
     * That phase has no run yet, its newest run is still going, or it succeeded — a succeeded phase has nothing to ask again
     */
    409: unknown;
};

export type PostCiApiRunsRerunResponses = {
    /**
     * A new run has been accepted and queued
     */
    202: RetryRunResponse;
};

export type PostCiApiRunsRerunResponse = PostCiApiRunsRerunResponses[keyof PostCiApiRunsRerunResponses];

export type GetCiApiRunsByRunIdData = {
    body?: never;
    path: {
        runId: string;
    };
    query?: never;
    url: '/ci/api/runs/{runId}';
};

export type GetCiApiRunsByRunIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such run
     */
    404: unknown;
};

export type GetCiApiRunsByRunIdResponses = {
    /**
     * The run
     */
    200: CiRunDto;
};

export type GetCiApiRunsByRunIdResponse = GetCiApiRunsByRunIdResponses[keyof GetCiApiRunsByRunIdResponses];

export type GetCiApiRunsByRunIdBaselineData = {
    body?: never;
    path: {
        runId: string;
    };
    query?: never;
    url: '/ci/api/runs/{runId}/baseline';
};

export type GetCiApiRunsByRunIdBaselineErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such run
     */
    404: unknown;
};

export type GetCiApiRunsByRunIdBaselineResponses = {
    /**
     * The baseline, or {"baseline":null}
     */
    200: CiBaselineAnswer;
};

export type GetCiApiRunsByRunIdBaselineResponse = GetCiApiRunsByRunIdBaselineResponses[keyof GetCiApiRunsByRunIdBaselineResponses];

export type GetCiApiRunsByRunIdBaselineReportsByKindData = {
    body?: never;
    path: {
        kind: string;
        runId: string;
    };
    query?: never;
    url: '/ci/api/runs/{runId}/baseline/reports/{kind}';
};

export type GetCiApiRunsByRunIdBaselineReportsByKindErrors = {
    /**
     * A bad kind name
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such run
     */
    404: unknown;
};

export type GetCiApiRunsByRunIdBaselineReportsByKindResponses = {
    /**
     * The reports; [] when there is no baseline or none
     */
    200: Array<CiReportDto>;
};

export type GetCiApiRunsByRunIdBaselineReportsByKindResponse = GetCiApiRunsByRunIdBaselineReportsByKindResponses[keyof GetCiApiRunsByRunIdBaselineReportsByKindResponses];

export type PostCiApiRunsByRunIdCancelData = {
    /**
     * Optional human-readable cancellation reason
     */
    body?: CancelRunRequest;
    path: {
        runId: string;
    };
    query?: never;
    url: '/ci/api/runs/{runId}/cancel';
};

export type PostCiApiRunsByRunIdCancelErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such run
     */
    404: unknown;
    /**
     * The run has already finished, so there is nothing to stop
     */
    409: unknown;
};

export type PostCiApiRunsByRunIdCancelResponses = {
    /**
     * The run has been stopped or asked to stop
     */
    202: unknown;
};

export type GetCiApiRunsByRunIdReportsData = {
    body?: never;
    path: {
        runId: string;
    };
    query?: never;
    url: '/ci/api/runs/{runId}/reports';
};

export type GetCiApiRunsByRunIdReportsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such run
     */
    404: unknown;
};

export type GetCiApiRunsByRunIdReportsResponses = {
    /**
     * The run's reports; an empty list when it has none
     */
    200: CiRunReportsDto;
};

export type GetCiApiRunsByRunIdReportsResponse = GetCiApiRunsByRunIdReportsResponses[keyof GetCiApiRunsByRunIdReportsResponses];

export type GetCiApiRunsByRunIdReportsByReportIdData = {
    body?: never;
    path: {
        reportId: string;
        runId: string;
    };
    query?: never;
    url: '/ci/api/runs/{runId}/reports/{reportId}';
};

export type GetCiApiRunsByRunIdReportsByReportIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such run, or no such report on it
     */
    404: unknown;
};

export type GetCiApiRunsByRunIdReportsByReportIdResponses = {
    /**
     * The report
     */
    200: CiReportDto;
};

export type GetCiApiRunsByRunIdReportsByReportIdResponse = GetCiApiRunsByRunIdReportsByReportIdResponses[keyof GetCiApiRunsByRunIdReportsByReportIdResponses];

export type PostCiApiRunsByRunIdRetryData = {
    body?: never;
    path: {
        runId: string;
    };
    query?: never;
    url: '/ci/api/runs/{runId}/retry';
};

export type PostCiApiRunsByRunIdRetryErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * The token covers this run's repository for nobody — no project claim and no platform-wide role, or a project claim this instance cannot place the repository in
     */
    403: unknown;
    /**
     * No such run
     */
    404: unknown;
    /**
     * The run has not finished, so there is nothing to retry yet
     */
    409: unknown;
};

export type PostCiApiRunsByRunIdRetryResponses = {
    /**
     * A new run has been accepted and queued
     */
    202: RetryRunResponse;
};

export type PostCiApiRunsByRunIdRetryResponse = PostCiApiRunsByRunIdRetryResponses[keyof PostCiApiRunsByRunIdRetryResponses];

export type PutCiApiRunsByRunIdStepsByStepIndexReportsByKindData = {
    body: CiReportSubmission;
    path: {
        kind: string;
        runId: string;
        stepIndex: number;
    };
    query?: never;
    url: '/ci/api/runs/{runId}/steps/{stepIndex}/reports/{kind}';
};

export type PutCiApiRunsByRunIdStepsByStepIndexReportsByKindErrors = {
    /**
     * A bad kind name, body, or more than 10 highlights
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * The token is not this run's
     */
    403: unknown;
    /**
     * No such run
     */
    404: unknown;
    /**
     * The run is not RUNNING
     */
    409: unknown;
    /**
     * The body is larger than 1 MiB
     */
    413: unknown;
};

export type PutCiApiRunsByRunIdStepsByStepIndexReportsByKindResponses = {
    /**
     * Stored, replacing any earlier report of the kind
     */
    204: void;
};

export type PutCiApiRunsByRunIdStepsByStepIndexReportsByKindResponse = PutCiApiRunsByRunIdStepsByStepIndexReportsByKindResponses[keyof PutCiApiRunsByRunIdStepsByStepIndexReportsByKindResponses];
