// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, ServerSentEventsResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteEventsApiEventsByIdData, DeleteEventsApiEventsByIdErrors, DeleteEventsApiEventsByIdResponses, GetEventsApiEventsByIdData, GetEventsApiEventsByIdErrors, GetEventsApiEventsByIdResponses, GetEventsApiEventsNamesData, GetEventsApiEventsNamesErrors, GetEventsApiEventsNamesResponses, GetEventsApiStreamData, GetEventsApiStreamErrors, GetEventsApiStreamResponse, GetEventsApiStreamResponses, ListEventsData, ListEventsErrors, ListEventsResponses, PostEventsApiEventsData, PostEventsApiEventsErrors, PostEventsApiEventsResponses, PutEventsApiEventsByIdData, PutEventsApiEventsByIdErrors, PutEventsApiEventsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List
 */
export const listEvents = <ThrowOnError extends boolean = false>(options?: Options<ListEventsData, ThrowOnError>): RequestResult<ListEventsResponses, ListEventsErrors, ThrowOnError> => (options?.client ?? client).get<ListEventsResponses, ListEventsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/api/events',
    ...options
});

/**
 * Create
 */
export const postEventsApiEvents = <ThrowOnError extends boolean = false>(options: Options<PostEventsApiEventsData, ThrowOnError>): RequestResult<PostEventsApiEventsResponses, PostEventsApiEventsErrors, ThrowOnError> => (options.client ?? client).post<PostEventsApiEventsResponses, PostEventsApiEventsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/api/events',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Names
 */
export const getEventsApiEventsNames = <ThrowOnError extends boolean = false>(options?: Options<GetEventsApiEventsNamesData, ThrowOnError>): RequestResult<GetEventsApiEventsNamesResponses, GetEventsApiEventsNamesErrors, ThrowOnError> => (options?.client ?? client).get<GetEventsApiEventsNamesResponses, GetEventsApiEventsNamesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/api/events/names',
    ...options
});

/**
 * Delete
 */
export const deleteEventsApiEventsById = <ThrowOnError extends boolean = false>(options: Options<DeleteEventsApiEventsByIdData, ThrowOnError>): RequestResult<DeleteEventsApiEventsByIdResponses, DeleteEventsApiEventsByIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteEventsApiEventsByIdResponses, DeleteEventsApiEventsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/api/events/{id}',
    ...options
});

/**
 * Get
 */
export const getEventsApiEventsById = <ThrowOnError extends boolean = false>(options: Options<GetEventsApiEventsByIdData, ThrowOnError>): RequestResult<GetEventsApiEventsByIdResponses, GetEventsApiEventsByIdErrors, ThrowOnError> => (options.client ?? client).get<GetEventsApiEventsByIdResponses, GetEventsApiEventsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/api/events/{id}',
    ...options
});

/**
 * Publish
 */
export const putEventsApiEventsById = <ThrowOnError extends boolean = false>(options: Options<PutEventsApiEventsByIdData, ThrowOnError>): RequestResult<PutEventsApiEventsByIdResponses, PutEventsApiEventsByIdErrors, ThrowOnError> => (options.client ?? client).put<PutEventsApiEventsByIdResponses, PutEventsApiEventsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/api/events/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Live event stream (Server-Sent Events)
 *
 * Pushes each newly created event whose name is named by ?names= (comma-separated; '*' means everything; absent means nothing) as an SSE event whose id: field is the event id and whose data is the EventCreated envelope. Live only: no replay, no offset, no catch-up.
 */
export const getEventsApiStream = <ThrowOnError extends boolean = false>(options?: Options<GetEventsApiStreamData, ThrowOnError, GetEventsApiStreamResponse>): Promise<ServerSentEventsResult<GetEventsApiStreamResponses>> => (options?.client ?? client).sse.get<GetEventsApiStreamResponses, GetEventsApiStreamErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/api/stream',
    ...options
});
