// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CreateEventRequest = {
    name: string;
    occurredAt?: Instant;
    payload?: string;
    description?: string;
    parentId?: string;
    environment?: string;
};

export type EventDto = {
    id?: string;
    name?: string;
    occurredAt?: Instant;
    payload?: string;
    description?: string;
    parentId?: string;
    environment?: string;
    createdAt?: Instant;
    updatedAt?: Instant;
};

export type Instant = string;

export type PublishEventRequest = {
    name: string;
    occurredAt: Instant;
    payload?: string;
    description?: string;
    parentId?: string;
    environment?: string;
};

export type Response = {
    event?: EventDto;
};

export type Response1 = {
    names?: Array<string>;
};

export type Response2 = {
    events?: Array<EventDto>;
    nextCursor?: string;
};

export type Response3 = {
    event?: EventDto;
};

export type Response4 = {
    success?: boolean;
};

export type Response5 = {
    event?: EventDto;
};

export type ListEventsData = {
    body?: never;
    path?: never;
    query?: {
        attr?: Array<string>;
        cursor?: string;
        environment?: string;
        limit?: string;
        name?: string;
        order?: string;
        parentId?: string;
        q?: string;
        since?: string;
    };
    url: '/events/api/events';
};

export type ListEventsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type ListEventsResponses = {
    /**
     * OK
     */
    200: Response2;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];

export type PostEventsApiEventsData = {
    body: CreateEventRequest;
    path?: never;
    query?: never;
    url: '/events/api/events';
};

export type PostEventsApiEventsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostEventsApiEventsResponses = {
    /**
     * OK
     */
    200: Response5;
};

export type PostEventsApiEventsResponse = PostEventsApiEventsResponses[keyof PostEventsApiEventsResponses];

export type GetEventsApiEventsNamesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/events/api/events/names';
};

export type GetEventsApiEventsNamesErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetEventsApiEventsNamesResponses = {
    /**
     * OK
     */
    200: Response1;
};

export type GetEventsApiEventsNamesResponse = GetEventsApiEventsNamesResponses[keyof GetEventsApiEventsNamesResponses];

export type DeleteEventsApiEventsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/events/api/events/{id}';
};

export type DeleteEventsApiEventsByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type DeleteEventsApiEventsByIdResponses = {
    /**
     * OK
     */
    200: Response4;
};

export type DeleteEventsApiEventsByIdResponse = DeleteEventsApiEventsByIdResponses[keyof DeleteEventsApiEventsByIdResponses];

export type GetEventsApiEventsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/events/api/events/{id}';
};

export type GetEventsApiEventsByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetEventsApiEventsByIdResponses = {
    /**
     * OK
     */
    200: Response3;
};

export type GetEventsApiEventsByIdResponse = GetEventsApiEventsByIdResponses[keyof GetEventsApiEventsByIdResponses];

export type PutEventsApiEventsByIdData = {
    body: PublishEventRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/events/api/events/{id}';
};

export type PutEventsApiEventsByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PutEventsApiEventsByIdResponses = {
    /**
     * OK
     */
    200: Response;
};

export type PutEventsApiEventsByIdResponse = PutEventsApiEventsByIdResponses[keyof PutEventsApiEventsByIdResponses];

export type GetEventsApiStreamData = {
    body?: never;
    path?: never;
    query?: {
        names?: string;
    };
    url: '/events/api/stream';
};

export type GetEventsApiStreamErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetEventsApiStreamResponses = {
    /**
     * An open SSE stream. Each event carries the event id in its id: field and the EventCreated envelope's JSON in its data: field; comment lines mark the open and keep the connection alive. The body never ends.
     */
    200: string;
};

export type GetEventsApiStreamResponse = GetEventsApiStreamResponses[keyof GetEventsApiStreamResponses];
