// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AddAttachmentRequest = {
    mimeType?: string;
    label: string;
    source: string;
    dataBase64: string;
};

export type AgentActivityState = 'IDLE' | 'BUSY' | 'WAITING' | 'ENDED';

export type AgentLaunch = 'SCHEDULED' | 'SKIPPED_RUNNING';

/**
 * The error envelope: a message, plus a reason on a 409.
 */
export type ApiError = {
    /**
     * What went wrong, in words. Always present.
     */
    message?: string;
    /**
     * Which refusal this is. Present on the 409s the release and integrate flows raise, absent on every other error. A value a client does not recognise is shown as the message verbatim.
     */
    reason?: Reason;
    /**
     * The conflicted paths. Present only for CONFLICT and MERGE_CONFLICT.
     */
    conflicts?: Array<string>;
};

export type ArchivedSessionDto = {
    sessionId?: string;
    startedAt?: Instant;
    endedAt?: Instant;
    messageCount?: number;
    subagents?: Array<ArchivedSubagentDto>;
};

export type ArchivedSubagentDto = {
    agentId?: string;
    agentType?: string;
    description?: string;
    messageCount?: number;
};

export type BlockedMark = {
    workspaceId?: number;
    applied?: boolean;
};

export type BootstrapOutcome = 'SKIPPED' | 'SUCCEEDED' | 'FAILED';

export type BootstrapRunDto = {
    bootstrapCommandId?: string;
    commandName?: string;
    outcome?: BootstrapOutcome;
    commandId?: string;
    exitCode?: number;
    ranAt?: Instant;
};

export type BranchResolution = {
    resolved?: boolean;
    workspaceId?: number;
};

export type BranchSweepReport = {
    dryRun?: boolean;
    repositoriesExamined?: number;
    branchesExamined?: number;
    removed?: Array<SweptBranch>;
    errors?: Array<SweepError>;
};

export type CleanupBranchRequest = {
    branch: string;
    result?: string;
};

export type CreateWorkspaceRequest = {
    repositoryId: string;
    id: string;
    parent?: string;
    branch?: string;
    preamble?: string;
    adoptExisting?: boolean;
    branchTree?: boolean;
    admin?: boolean;
};

export type DeliverTurnRequest = {
    repositoryId: string;
    branch: string;
    text: string;
    compactFirst?: boolean;
    workId?: string;
};

export type Delivery = {
    workspaceId?: number;
    delivered?: boolean;
    launched?: boolean;
    detail?: string;
};

export type DiscardWorkspaceRequest = {
    result?: string;
};

export type Dispatch = {
    workspace?: WorkspaceDto;
    fresh?: boolean;
    agentLaunch?: AgentLaunch;
    technicalProcessId?: string;
};

export type DispatchAgentRequest = {
    repositoryId: string;
    branch: string;
    branchTree?: boolean;
    preamble?: string;
    ticketId?: string;
    epicId?: string;
    entityId?: string;
    entityTitle?: string;
    entityStatus?: string;
    entityBlocked?: boolean;
    instruction?: string;
    gitRefs?: Array<string>;
    workId?: string;
};

export type Entry = {
    workspace?: WorkspaceSubjectRefDto;
};

export type Entry1 = {
    workspace?: WorkspaceDto;
};

export type Entry2 = {
    workspace?: WorkspaceHistoryDto;
};

export type Instant = string;

export type IntegrateRequest = {
    summary: string;
};

export type LaunchPin = {
    image?: string;
    version?: string;
    launches?: string;
};

export type LaunchPins = {
    generatedAt?: Instant;
    pins?: Array<LaunchPin>;
};

export type MarkBlockedRequest = {
    repositoryId: string;
    branch: string;
    blocked?: boolean;
    workId?: string;
};

export type MarkEntityRequest = {
    repositoryId: string;
    branch: string;
    title?: string;
    status?: string;
    blocked: boolean;
    workId?: string;
};

export type MergeBranchRequest = {
    source: string;
    target?: string;
    result?: string;
};

export type MergeWorkspaceRequest = {
    target?: string;
};

export type PromptAttachmentSource = 'SKETCH' | 'PASTE';

export type Reason = 'CONFLICT' | 'MERGE_CONFLICT' | 'NOT_FAST_FORWARD' | 'ALREADY_INTEGRATED' | 'PUSH_REJECTED' | 'RELEASE_REQUIRED';

export type ResolveReleasedBranchRequest = {
    branch: string;
    target?: string;
    commit?: string;
    result?: string;
};

export type Response = {
    entries?: Array<Entry>;
};

export type Response1 = {
    commitHash?: string;
    hasConflicts?: boolean;
    output?: string;
    cleanedUp?: boolean;
};

export type Response10 = {
    workspace?: WorkspaceDto;
    technicalProcessId?: string;
};

export type Response11 = {
    success?: boolean;
};

export type Response12 = {
    workspace?: WorkspaceDto;
};

export type Response13 = {
    technicalProcessId?: string;
};

export type Response14 = {
    workspace?: WorkspaceHistoryDetailDto;
};

export type Response15 = {
    entries?: Array<Entry2>;
};

export type Response16 = {
    workspace?: WorkspaceHistoryDetailDto;
};

export type Response17 = {
    lines?: Array<string>;
};

export type Response18 = {
    sessions?: Array<ArchivedSessionDto>;
};

export type Response19 = {
    id?: string;
    mimeType?: string;
    label?: string;
    source?: PromptAttachmentSource;
    createdAt?: Instant;
};

export type Response2 = {
    success?: boolean;
};

export type Response20 = {
    attachments?: Array<WorkspacePromptAttachmentDataDto>;
};

export type Response21 = {
    draft?: WorkspacePromptDraftDto;
};

export type Response22 = {
    draft?: WorkspacePromptDraftDto;
};

export type Response3 = {
    events?: Array<ServiceEventDto>;
};

export type Response4 = {
    runs?: Array<BootstrapRunDto>;
};

export type Response5 = {
    workspace?: WorkspaceDto;
    technicalProcessId?: string;
};

export type Response6 = {
    commitHash?: string;
    hasConflicts?: boolean;
    output?: string;
};

export type Response7 = {
    entries?: Array<Entry1>;
};

export type Response8 = {
    commitSha?: string;
    branch?: string;
    targetBranch?: string;
};

export type Response9 = {
    workspace?: WorkspaceDto;
};

export type SavePromptDraftRequest = {
    content: string;
    serializedPrompt?: string;
};

export type ServiceEventDto = {
    repoId?: string;
    workspaceId?: string;
    workspaceRowId?: number;
    serviceId?: string;
    serviceName?: string;
    kind?: ServiceEventKind;
    severity?: ServiceEventSeverity;
    status?: ServiceStatus;
    summary?: string;
    logExcerpt?: string;
    commandId?: string;
    source?: string;
    anchorFrom?: number;
    anchorTo?: number;
    sourceEpoch?: Instant;
    timestamp?: Instant;
};

export type ServiceEventKind = 'STATUS_CHANGED';

export type ServiceEventSeverity = 'INFO' | 'WARNING' | 'ERROR';

export type ServiceStatus = 'STARTING' | 'READY' | 'RESTARTING' | 'CRASHED' | 'STOPPED';

export type SweepBranchesRequest = {
    dryRun?: boolean;
    repositories: Array<SweepRepository>;
    keepPrefixes?: Array<string>;
};

export type SweepError = {
    repositoryId?: string;
    branch?: string;
    error?: string;
};

export type SweepRepository = {
    id?: string;
    name?: string;
    mainBranch?: string;
};

export type SweptBranch = {
    repositoryId?: string;
    repositoryName?: string;
    branch?: string;
};

export type UpdateHistoryRequest = {
    preamble?: string;
    result?: string;
};

export type WorkItemWorkspaceDto = {
    id?: number;
    workId?: string;
    qualifiedId?: string;
    repositoryId?: string;
    workspaceId?: string;
    branch?: string;
    status?: string;
    runtimeStatus?: string;
    createdAt?: Instant;
    resolvedAt?: Instant;
};

export type WorkItemWorkspaceEntry = {
    workspace?: WorkItemWorkspaceDto;
};

export type WorkItemWorkspaces = {
    entries?: Array<WorkItemWorkspaceEntry>;
};

export type WorkspaceDto = {
    id?: number;
    workspaceId?: string;
    parent?: string;
    branch?: string;
    repositoryMainBranch?: string;
    ahead?: number;
    behind?: number;
    conflictsWithParent?: boolean;
    status?: WorkspaceStatus;
    runtimeStatus?: WorkspaceRuntimeStatus;
    runtimeError?: string;
    clean?: boolean;
    agentActivity?: AgentActivityState;
    preamble?: string;
    ticketId?: string;
    epicId?: string;
    result?: string;
    createdAt?: Instant;
    resolvedAt?: Instant;
    daemonConnectedAt?: Instant;
    daemonVersion?: string;
    daemonBuildTime?: Instant;
    daemonOutdated?: boolean;
    admin?: boolean;
};

export type WorkspaceEventDto = {
    type?: WorkspaceEventType;
    branch?: string;
    parent?: string;
    target?: string;
    commit?: string;
    note?: string;
    at?: Instant;
};

export type WorkspaceEventType = 'CREATED' | 'MERGED' | 'UPDATED_FROM_PARENT' | 'INTEGRATED' | 'ABANDONED';

export type WorkspaceHistoryDetailDto = {
    id?: number;
    workspaceId?: string;
    parent?: string;
    status?: WorkspaceStatus;
    preamble?: string;
    result?: string;
    createdAt?: Instant;
    resolvedAt?: Instant;
    events?: Array<WorkspaceEventDto>;
};

export type WorkspaceHistoryDto = {
    id?: number;
    workspaceId?: string;
    parent?: string;
    status?: WorkspaceStatus;
    createdAt?: Instant;
    resolvedAt?: Instant;
};

export type WorkspacePromptAttachmentDataDto = {
    id?: string;
    mimeType?: string;
    label?: string;
    source?: PromptAttachmentSource;
    createdAt?: Instant;
    dataBase64?: string;
};

export type WorkspacePromptDraftDto = {
    content?: string;
    serializedPrompt?: string;
    promptVersion?: number;
    lastRunAt?: Instant;
    lastRunPromptVersion?: number;
    lastRunCommandId?: string;
    updatedAt?: Instant;
};

export type WorkspaceRuntimeStatus = 'RUNNING' | 'STOPPED' | 'PROVISIONING' | 'FAILED';

export type WorkspaceStatus = 'ACTIVE' | 'INTEGRATED' | 'ABANDONED';

export type WorkspaceSubjectRefDto = {
    workspaceRowId?: number;
    repositoryId?: string;
    workspaceId?: string;
    branch?: string;
    ticketId?: string;
    epicId?: string;
    status?: string;
    resolvedAt?: Instant;
    workId?: string;
    entityId?: string;
};

export type DispatchAgentData = {
    body: DispatchAgentRequest;
    path?: never;
    query?: never;
    url: '/workspaces/api/agent-dispatches';
};

export type DispatchAgentErrors = {
    /**
     * A blank repository or branch, a branch name git will not take, or a `gitRefs` list that breaks the rules (every entry under `refs/heads/`, `*` only as a trailing `*`, at most 500 entries of at most 255 characters, no duplicates).
     */
    400: ApiError;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such repository. Nothing was created.
     */
    404: ApiError;
};

export type DispatchAgentError = DispatchAgentErrors[keyof DispatchAgentErrors];

export type DispatchAgentResponses = {
    /**
     * Dispatched. `fresh:false` means the branch already had a workspace and it was answered instead — the ordinary case on a re-press, and not an error.
     */
    200: Dispatch;
};

export type DispatchAgentResponse = DispatchAgentResponses[keyof DispatchAgentResponses];

export type PostWorkspacesApiAgentDispatchesBlockedData = {
    body: MarkBlockedRequest;
    path?: never;
    query?: never;
    url: '/workspaces/api/agent-dispatches/blocked';
};

export type PostWorkspacesApiAgentDispatchesBlockedErrors = {
    /**
     * A blank repository or branch.
     */
    400: ApiError;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostWorkspacesApiAgentDispatchesBlockedError = PostWorkspacesApiAgentDispatchesBlockedErrors[keyof PostWorkspacesApiAgentDispatchesBlockedErrors];

export type PostWorkspacesApiAgentDispatchesBlockedResponses = {
    /**
     * Answered. `workspaceId: null` means no workspace stands on that branch; `applied: false` with a non-null `workspaceId` means the daemon was not reachable or did not take the marker. Neither is an error — this door never creates a workspace, ensures a container or starts an agent.
     */
    200: BlockedMark;
};

export type PostWorkspacesApiAgentDispatchesBlockedResponse = PostWorkspacesApiAgentDispatchesBlockedResponses[keyof PostWorkspacesApiAgentDispatchesBlockedResponses];

export type PostWorkspacesApiAgentDispatchesDeliveryData = {
    body: DeliverTurnRequest;
    path?: never;
    query?: never;
    url: '/workspaces/api/agent-dispatches/delivery';
};

export type PostWorkspacesApiAgentDispatchesDeliveryErrors = {
    /**
     * A blank repository, branch or text.
     */
    400: ApiError;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostWorkspacesApiAgentDispatchesDeliveryError = PostWorkspacesApiAgentDispatchesDeliveryErrors[keyof PostWorkspacesApiAgentDispatchesDeliveryErrors];

export type PostWorkspacesApiAgentDispatchesDeliveryResponses = {
    /**
     * Answered. `workspaceId: null` means no workspace stands on that branch — nothing was said and nothing was created, which is a normal outcome and not an error.
     */
    200: Delivery;
};

export type PostWorkspacesApiAgentDispatchesDeliveryResponse = PostWorkspacesApiAgentDispatchesDeliveryResponses[keyof PostWorkspacesApiAgentDispatchesDeliveryResponses];

export type PostWorkspacesApiAgentDispatchesEntityData = {
    body: MarkEntityRequest;
    path?: never;
    query?: never;
    url: '/workspaces/api/agent-dispatches/entity';
};

export type PostWorkspacesApiAgentDispatchesEntityErrors = {
    /**
     * A blank repository or branch, or a missing or non-boolean `blocked`.
     */
    400: ApiError;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostWorkspacesApiAgentDispatchesEntityError = PostWorkspacesApiAgentDispatchesEntityErrors[keyof PostWorkspacesApiAgentDispatchesEntityErrors];

export type PostWorkspacesApiAgentDispatchesEntityResponses = {
    /**
     * Answered. `workspaceId: null` means no workspace stands on that branch and nothing was stored; otherwise the facts are stored on the workspace, and `applied` says whether its daemon also took them live. Never creates a workspace, ensures a container or starts an agent.
     */
    200: BlockedMark;
};

export type PostWorkspacesApiAgentDispatchesEntityResponse = PostWorkspacesApiAgentDispatchesEntityResponses[keyof PostWorkspacesApiAgentDispatchesEntityResponses];

export type GetWorkspacesApiAgentDispatchesReferencesData = {
    body?: never;
    path?: never;
    query?: {
        epicId?: Array<string>;
        ticketId?: Array<string>;
        workId?: Array<string>;
    };
    url: '/workspaces/api/agent-dispatches/references';
};

export type GetWorkspacesApiAgentDispatchesReferencesErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetWorkspacesApiAgentDispatchesReferencesResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetWorkspacesApiAgentDispatchesReferencesResponse = GetWorkspacesApiAgentDispatchesReferencesResponses[keyof GetWorkspacesApiAgentDispatchesReferencesResponses];

export type PostWorkspacesApiBranchesCleanupData = {
    body: CleanupBranchRequest;
    path?: never;
    query?: {
        repositoryId?: string;
    };
    url: '/workspaces/api/branches/cleanup';
};

export type PostWorkspacesApiBranchesCleanupErrors = {
    /**
     * The branch is not eligible: uncommitted changes, unmerged commits, or dependents.
     */
    400: ApiError;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such repository.
     */
    404: ApiError;
};

export type PostWorkspacesApiBranchesCleanupError = PostWorkspacesApiBranchesCleanupErrors[keyof PostWorkspacesApiBranchesCleanupErrors];

export type PostWorkspacesApiBranchesCleanupResponses = {
    /**
     * Removed.
     */
    200: Response2;
};

export type PostWorkspacesApiBranchesCleanupResponse = PostWorkspacesApiBranchesCleanupResponses[keyof PostWorkspacesApiBranchesCleanupResponses];

export type PostWorkspacesApiBranchesMergeData = {
    body: MergeBranchRequest;
    path?: never;
    query?: {
        repositoryId?: string;
    };
    url: '/workspaces/api/branches/merge';
};

export type PostWorkspacesApiBranchesMergeErrors = {
    /**
     * A blank, dash-leading or self-referential branch name.
     */
    400: ApiError;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such repository.
     */
    404: ApiError;
    /**
     * The target is the repository's default branch. `reason` is RELEASE_REQUIRED and the message names the release flow that does write it.
     */
    409: ApiError;
};

export type PostWorkspacesApiBranchesMergeError = PostWorkspacesApiBranchesMergeErrors[keyof PostWorkspacesApiBranchesMergeErrors];

export type PostWorkspacesApiBranchesMergeResponses = {
    /**
     * Merged.
     */
    200: Response1;
};

export type PostWorkspacesApiBranchesMergeResponse = PostWorkspacesApiBranchesMergeResponses[keyof PostWorkspacesApiBranchesMergeResponses];

export type PostWorkspacesApiBranchesResolutionData = {
    body: ResolveReleasedBranchRequest;
    path?: never;
    query?: {
        repositoryId?: string;
    };
    url: '/workspaces/api/branches/resolution';
};

export type PostWorkspacesApiBranchesResolutionErrors = {
    /**
     * A blank branch, or the repository's main workspace — refused on both belts: the row has no parent, or the branch is the repository's default branch.
     */
    400: ApiError;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such repository.
     */
    404: ApiError;
};

export type PostWorkspacesApiBranchesResolutionError = PostWorkspacesApiBranchesResolutionErrors[keyof PostWorkspacesApiBranchesResolutionErrors];

export type PostWorkspacesApiBranchesResolutionResponses = {
    /**
     * Resolved, or `resolved:false` when no active workspace stood on the branch — the ordinary case, and what a repeated call answers.
     */
    200: BranchResolution;
};

export type PostWorkspacesApiBranchesResolutionResponse = PostWorkspacesApiBranchesResolutionResponses[keyof PostWorkspacesApiBranchesResolutionResponses];

export type EnsureEditorData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workspaces/api/editor/ensure';
};

export type EnsureEditorErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type EnsureEditorResponses = {
    /**
     * The editor was already there.
     */
    200: unknown;
    /**
     * The editor was started by this call.
     */
    201: unknown;
};

export type PostWorkspacesApiGcBranchesData = {
    body: SweepBranchesRequest;
    path?: never;
    query?: never;
    url: '/workspaces/api/gc/branches';
};

export type PostWorkspacesApiGcBranchesErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostWorkspacesApiGcBranchesResponses = {
    /**
     * OK
     */
    200: BranchSweepReport;
};

export type PostWorkspacesApiGcBranchesResponse = PostWorkspacesApiGcBranchesResponses[keyof PostWorkspacesApiGcBranchesResponses];

export type GetWorkspacesApiHistoryData = {
    body?: never;
    path?: never;
    query?: {
        repositoryId?: string;
    };
    url: '/workspaces/api/history';
};

export type GetWorkspacesApiHistoryErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetWorkspacesApiHistoryResponses = {
    /**
     * OK
     */
    200: Response15;
};

export type GetWorkspacesApiHistoryResponse = GetWorkspacesApiHistoryResponses[keyof GetWorkspacesApiHistoryResponses];

export type GetWorkspacesApiHistoryByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/history/{id}';
};

export type GetWorkspacesApiHistoryByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetWorkspacesApiHistoryByIdResponses = {
    /**
     * OK
     */
    200: Response16;
};

export type GetWorkspacesApiHistoryByIdResponse = GetWorkspacesApiHistoryByIdResponses[keyof GetWorkspacesApiHistoryByIdResponses];

export type PatchWorkspacesApiHistoryByIdData = {
    body: UpdateHistoryRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/history/{id}';
};

export type PatchWorkspacesApiHistoryByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PatchWorkspacesApiHistoryByIdResponses = {
    /**
     * OK
     */
    200: Response14;
};

export type PatchWorkspacesApiHistoryByIdResponse = PatchWorkspacesApiHistoryByIdResponses[keyof PatchWorkspacesApiHistoryByIdResponses];

export type GetWorkspacesApiHistoryByIdAgentSessionsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/history/{id}/agent-sessions';
};

export type GetWorkspacesApiHistoryByIdAgentSessionsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetWorkspacesApiHistoryByIdAgentSessionsResponses = {
    /**
     * OK
     */
    200: Response18;
};

export type GetWorkspacesApiHistoryByIdAgentSessionsResponse = GetWorkspacesApiHistoryByIdAgentSessionsResponses[keyof GetWorkspacesApiHistoryByIdAgentSessionsResponses];

export type GetWorkspacesApiHistoryByIdAgentSessionsBySessionIdTranscriptData = {
    body?: never;
    path: {
        id: number;
        sessionId: string;
    };
    query?: never;
    url: '/workspaces/api/history/{id}/agent-sessions/{sessionId}/transcript';
};

export type GetWorkspacesApiHistoryByIdAgentSessionsBySessionIdTranscriptErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetWorkspacesApiHistoryByIdAgentSessionsBySessionIdTranscriptResponses = {
    /**
     * OK
     */
    200: Response17;
};

export type GetWorkspacesApiHistoryByIdAgentSessionsBySessionIdTranscriptResponse = GetWorkspacesApiHistoryByIdAgentSessionsBySessionIdTranscriptResponses[keyof GetWorkspacesApiHistoryByIdAgentSessionsBySessionIdTranscriptResponses];

export type GetWorkspacesApiPinsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workspaces/api/pins';
};

export type GetWorkspacesApiPinsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetWorkspacesApiPinsResponses = {
    /**
     * The effective launch pins, image order
     */
    200: LaunchPins;
};

export type GetWorkspacesApiPinsResponse = GetWorkspacesApiPinsResponses[keyof GetWorkspacesApiPinsResponses];

export type GetWorkspacesApiServiceEventsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        repoId?: string;
        severity?: ServiceEventSeverity;
        since?: Instant;
        source?: string;
        workspaceId?: string;
    };
    url: '/workspaces/api/service-events';
};

export type GetWorkspacesApiServiceEventsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetWorkspacesApiServiceEventsResponses = {
    /**
     * OK
     */
    200: Response3;
};

export type GetWorkspacesApiServiceEventsResponse = GetWorkspacesApiServiceEventsResponses[keyof GetWorkspacesApiServiceEventsResponses];

export type ListOpenWorkspacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workspaces/api/work/workspaces';
};

export type ListOpenWorkspacesErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type ListOpenWorkspacesResponses = {
    /**
     * OK
     */
    200: WorkItemWorkspaces;
};

export type ListOpenWorkspacesResponse = ListOpenWorkspacesResponses[keyof ListOpenWorkspacesResponses];

export type ListWorkItemWorkspacesData = {
    body?: never;
    path: {
        workRef: string;
    };
    query?: never;
    url: '/workspaces/api/work/{workRef}/workspaces';
};

export type ListWorkItemWorkspacesErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type ListWorkItemWorkspacesResponses = {
    /**
     * OK
     */
    200: WorkItemWorkspaces;
};

export type ListWorkItemWorkspacesResponse = ListWorkItemWorkspacesResponses[keyof ListWorkItemWorkspacesResponses];

export type GetWorkspacesApiWorkspacesData = {
    body?: never;
    path?: never;
    query?: {
        repositoryId?: string;
    };
    url: '/workspaces/api/workspaces';
};

export type GetWorkspacesApiWorkspacesErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetWorkspacesApiWorkspacesResponses = {
    /**
     * OK
     */
    200: Response7;
};

export type GetWorkspacesApiWorkspacesResponse = GetWorkspacesApiWorkspacesResponses[keyof GetWorkspacesApiWorkspacesResponses];

export type CreateWorkspaceData = {
    body: CreateWorkspaceRequest;
    path?: never;
    query?: never;
    url: '/workspaces/api/workspaces';
};

export type CreateWorkspaceErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type CreateWorkspaceResponses = {
    /**
     * OK
     */
    200: Response12;
};

export type CreateWorkspaceResponse = CreateWorkspaceResponses[keyof CreateWorkspaceResponses];

export type GetWorkspacesApiWorkspacesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}';
};

export type GetWorkspacesApiWorkspacesByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such ACTIVE workspace.
     */
    404: ApiError;
};

export type GetWorkspacesApiWorkspacesByIdError = GetWorkspacesApiWorkspacesByIdErrors[keyof GetWorkspacesApiWorkspacesByIdErrors];

export type GetWorkspacesApiWorkspacesByIdResponses = {
    /**
     * The workspace.
     */
    200: Response9;
};

export type GetWorkspacesApiWorkspacesByIdResponse = GetWorkspacesApiWorkspacesByIdResponses[keyof GetWorkspacesApiWorkspacesByIdResponses];

export type GetWorkspacesApiWorkspacesByIdActiveProcessData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/active-process';
};

export type GetWorkspacesApiWorkspacesByIdActiveProcessErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetWorkspacesApiWorkspacesByIdActiveProcessResponses = {
    /**
     * OK
     */
    200: Response13;
};

export type GetWorkspacesApiWorkspacesByIdActiveProcessResponse = GetWorkspacesApiWorkspacesByIdActiveProcessResponses[keyof GetWorkspacesApiWorkspacesByIdActiveProcessResponses];

export type GetWorkspacesApiWorkspacesByIdBootstrapRunsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/bootstrap-runs';
};

export type GetWorkspacesApiWorkspacesByIdBootstrapRunsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such ACTIVE workspace.
     */
    404: ApiError;
};

export type GetWorkspacesApiWorkspacesByIdBootstrapRunsError = GetWorkspacesApiWorkspacesByIdBootstrapRunsErrors[keyof GetWorkspacesApiWorkspacesByIdBootstrapRunsErrors];

export type GetWorkspacesApiWorkspacesByIdBootstrapRunsResponses = {
    /**
     * The last run of each bootstrap step.
     */
    200: Response4;
};

export type GetWorkspacesApiWorkspacesByIdBootstrapRunsResponse = GetWorkspacesApiWorkspacesByIdBootstrapRunsResponses[keyof GetWorkspacesApiWorkspacesByIdBootstrapRunsResponses];

export type PostWorkspacesApiWorkspacesByIdDeleteContainerData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/delete-container';
};

export type PostWorkspacesApiWorkspacesByIdDeleteContainerErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostWorkspacesApiWorkspacesByIdDeleteContainerResponses = {
    /**
     * OK
     */
    200: WorkspaceDto;
};

export type PostWorkspacesApiWorkspacesByIdDeleteContainerResponse = PostWorkspacesApiWorkspacesByIdDeleteContainerResponses[keyof PostWorkspacesApiWorkspacesByIdDeleteContainerResponses];

export type PostWorkspacesApiWorkspacesByIdDiscardData = {
    body: DiscardWorkspaceRequest;
    path: {
        id: number;
    };
    query?: {
        'ignore-changes'?: boolean;
    };
    url: '/workspaces/api/workspaces/{id}/discard';
};

export type PostWorkspacesApiWorkspacesByIdDiscardErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostWorkspacesApiWorkspacesByIdDiscardResponses = {
    /**
     * OK
     */
    200: Response11;
};

export type PostWorkspacesApiWorkspacesByIdDiscardResponse = PostWorkspacesApiWorkspacesByIdDiscardResponses[keyof PostWorkspacesApiWorkspacesByIdDiscardResponses];

export type PostWorkspacesApiWorkspacesByIdEnsureContainerData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/ensure-container';
};

export type PostWorkspacesApiWorkspacesByIdEnsureContainerErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostWorkspacesApiWorkspacesByIdEnsureContainerResponses = {
    /**
     * OK
     */
    200: Response10;
};

export type PostWorkspacesApiWorkspacesByIdEnsureContainerResponse = PostWorkspacesApiWorkspacesByIdEnsureContainerResponses[keyof PostWorkspacesApiWorkspacesByIdEnsureContainerResponses];

export type PostWorkspacesApiWorkspacesByIdIntegrateData = {
    body: IntegrateRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/integrate';
};

export type PostWorkspacesApiWorkspacesByIdIntegrateErrors = {
    /**
     * No summary, an oversized one, or a workspace with no branch to integrate.
     */
    400: ApiError;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such workspace.
     */
    404: ApiError;
    /**
     * Nothing landed and the target is unchanged — including when the parent is the default branch, which only the release flow writes. `reason` says which refusal.
     */
    409: ApiError;
};

export type PostWorkspacesApiWorkspacesByIdIntegrateError = PostWorkspacesApiWorkspacesByIdIntegrateErrors[keyof PostWorkspacesApiWorkspacesByIdIntegrateErrors];

export type PostWorkspacesApiWorkspacesByIdIntegrateResponses = {
    /**
     * Merged into the parent branch.
     */
    200: Response8;
};

export type PostWorkspacesApiWorkspacesByIdIntegrateResponse = PostWorkspacesApiWorkspacesByIdIntegrateResponses[keyof PostWorkspacesApiWorkspacesByIdIntegrateResponses];

export type MergeWorkspaceData = {
    body: MergeWorkspaceRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/merge';
};

export type MergeWorkspaceErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such workspace.
     */
    404: ApiError;
    /**
     * The target is the repository's default branch. Use /integrate, or ask qits-projects for a release request.
     */
    409: ApiError;
};

export type MergeWorkspaceError = MergeWorkspaceErrors[keyof MergeWorkspaceErrors];

export type MergeWorkspaceResponses = {
    /**
     * Merged.
     */
    200: Response6;
};

export type MergeWorkspaceResponse = MergeWorkspaceResponses[keyof MergeWorkspaceResponses];

export type GetWorkspacesApiWorkspacesByIdPromptAttachmentsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/prompt-attachments';
};

export type GetWorkspacesApiWorkspacesByIdPromptAttachmentsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such ACTIVE workspace.
     */
    404: ApiError;
};

export type GetWorkspacesApiWorkspacesByIdPromptAttachmentsError = GetWorkspacesApiWorkspacesByIdPromptAttachmentsErrors[keyof GetWorkspacesApiWorkspacesByIdPromptAttachmentsErrors];

export type GetWorkspacesApiWorkspacesByIdPromptAttachmentsResponses = {
    /**
     * The attachments, oldest first.
     */
    200: Response20;
};

export type GetWorkspacesApiWorkspacesByIdPromptAttachmentsResponse = GetWorkspacesApiWorkspacesByIdPromptAttachmentsResponses[keyof GetWorkspacesApiWorkspacesByIdPromptAttachmentsResponses];

export type PostWorkspacesApiWorkspacesByIdPromptAttachmentsData = {
    body: AddAttachmentRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/prompt-attachments';
};

export type PostWorkspacesApiWorkspacesByIdPromptAttachmentsErrors = {
    /**
     * Not valid base64, not a PNG or JPEG, or an unknown source.
     */
    400: ApiError;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such ACTIVE workspace.
     */
    404: ApiError;
    /**
     * The image exceeds the configured per-image byte cap.
     */
    413: ApiError;
};

export type PostWorkspacesApiWorkspacesByIdPromptAttachmentsError = PostWorkspacesApiWorkspacesByIdPromptAttachmentsErrors[keyof PostWorkspacesApiWorkspacesByIdPromptAttachmentsErrors];

export type PostWorkspacesApiWorkspacesByIdPromptAttachmentsResponses = {
    /**
     * Attached; the row without its bytes.
     */
    201: Response19;
};

export type PostWorkspacesApiWorkspacesByIdPromptAttachmentsResponse = PostWorkspacesApiWorkspacesByIdPromptAttachmentsResponses[keyof PostWorkspacesApiWorkspacesByIdPromptAttachmentsResponses];

export type DeleteWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdData = {
    body?: never;
    path: {
        attachmentId: string;
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/prompt-attachments/{attachmentId}';
};

export type DeleteWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such ACTIVE workspace, or no such attachment on it.
     */
    404: ApiError;
};

export type DeleteWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdError = DeleteWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdErrors[keyof DeleteWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdErrors];

export type DeleteWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdResponses = {
    /**
     * Removed.
     */
    204: void;
};

export type DeleteWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdResponse = DeleteWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdResponses[keyof DeleteWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdResponses];

export type PutWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdData = {
    body: AddAttachmentRequest;
    path: {
        attachmentId: string;
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/prompt-attachments/{attachmentId}';
};

export type PutWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdErrors = {
    /**
     * Not valid base64, not a PNG or JPEG, or an unknown source.
     */
    400: ApiError;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such ACTIVE workspace, or no such attachment on it.
     */
    404: ApiError;
    /**
     * The image exceeds the configured limit.
     */
    413: unknown;
};

export type PutWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdError = PutWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdErrors[keyof PutWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdErrors];

export type PutWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdResponses = {
    /**
     * Updated; the same row id is preserved.
     */
    200: Response19;
};

export type PutWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdResponse = PutWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdResponses[keyof PutWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdResponses];

export type GetWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdContentData = {
    body?: never;
    path: {
        attachmentId: string;
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/prompt-attachments/{attachmentId}/content';
};

export type GetWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdContentErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such ACTIVE workspace, or no such attachment on it.
     */
    404: ApiError;
};

export type GetWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdContentError = GetWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdContentErrors[keyof GetWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdContentErrors];

export type GetWorkspacesApiWorkspacesByIdPromptAttachmentsByAttachmentIdContentResponses = {
    /**
     * The stored PNG or JPEG bytes.
     */
    200: unknown;
};

export type DeleteWorkspacesApiWorkspacesByIdPromptDraftData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/prompt-draft';
};

export type DeleteWorkspacesApiWorkspacesByIdPromptDraftErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such ACTIVE workspace.
     */
    404: ApiError;
};

export type DeleteWorkspacesApiWorkspacesByIdPromptDraftError = DeleteWorkspacesApiWorkspacesByIdPromptDraftErrors[keyof DeleteWorkspacesApiWorkspacesByIdPromptDraftErrors];

export type DeleteWorkspacesApiWorkspacesByIdPromptDraftResponses = {
    /**
     * There is no draft for this workspace.
     */
    204: void;
};

export type DeleteWorkspacesApiWorkspacesByIdPromptDraftResponse = DeleteWorkspacesApiWorkspacesByIdPromptDraftResponses[keyof DeleteWorkspacesApiWorkspacesByIdPromptDraftResponses];

export type GetWorkspacesApiWorkspacesByIdPromptDraftData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/prompt-draft';
};

export type GetWorkspacesApiWorkspacesByIdPromptDraftErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such ACTIVE workspace, or it has no saved draft.
     */
    404: ApiError;
};

export type GetWorkspacesApiWorkspacesByIdPromptDraftError = GetWorkspacesApiWorkspacesByIdPromptDraftErrors[keyof GetWorkspacesApiWorkspacesByIdPromptDraftErrors];

export type GetWorkspacesApiWorkspacesByIdPromptDraftResponses = {
    /**
     * The saved draft.
     */
    200: Response22;
};

export type GetWorkspacesApiWorkspacesByIdPromptDraftResponse = GetWorkspacesApiWorkspacesByIdPromptDraftResponses[keyof GetWorkspacesApiWorkspacesByIdPromptDraftResponses];

export type PutWorkspacesApiWorkspacesByIdPromptDraftData = {
    body: SavePromptDraftRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/prompt-draft';
};

export type PutWorkspacesApiWorkspacesByIdPromptDraftErrors = {
    /**
     * The content is not a well-formed JSON document.
     */
    400: ApiError;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * No such ACTIVE workspace.
     */
    404: ApiError;
    /**
     * The draft exceeds the configured byte cap.
     */
    413: ApiError;
};

export type PutWorkspacesApiWorkspacesByIdPromptDraftError = PutWorkspacesApiWorkspacesByIdPromptDraftErrors[keyof PutWorkspacesApiWorkspacesByIdPromptDraftErrors];

export type PutWorkspacesApiWorkspacesByIdPromptDraftResponses = {
    /**
     * The persisted draft, with its fresh updatedAt.
     */
    200: Response21;
};

export type PutWorkspacesApiWorkspacesByIdPromptDraftResponse = PutWorkspacesApiWorkspacesByIdPromptDraftResponses[keyof PutWorkspacesApiWorkspacesByIdPromptDraftResponses];

export type PostWorkspacesApiWorkspacesByIdRecreateContainerData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/recreate-container';
};

export type PostWorkspacesApiWorkspacesByIdRecreateContainerErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostWorkspacesApiWorkspacesByIdRecreateContainerResponses = {
    /**
     * OK
     */
    200: Response5;
};

export type PostWorkspacesApiWorkspacesByIdRecreateContainerResponse = PostWorkspacesApiWorkspacesByIdRecreateContainerResponses[keyof PostWorkspacesApiWorkspacesByIdRecreateContainerResponses];

export type PostWorkspacesApiWorkspacesByIdStopContainerData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/workspaces/api/workspaces/{id}/stop-container';
};

export type PostWorkspacesApiWorkspacesByIdStopContainerErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostWorkspacesApiWorkspacesByIdStopContainerResponses = {
    /**
     * OK
     */
    200: WorkspaceDto;
};

export type PostWorkspacesApiWorkspacesByIdStopContainerResponse = PostWorkspacesApiWorkspacesByIdStopContainerResponses[keyof PostWorkspacesApiWorkspacesByIdStopContainerResponses];
